### ISSUE TITLE
New Docker image name/repository

### ISSUE THREAD

**Issue by mattmoyer** [kubernetes-sigs/aws-iam-authenticator#109]
The images are currently hosted under `gcr.io/heptio-images`. Now that the project has been transferred into the `kubernetes-sigs` org,  it seems like we should move those to a more appropriate registry. Is there a precedent for other SIG-AWS subprojects?

cc @nckturner @mattlandis

**Comment by nckturner** [comment]
I don't know of a precedent, but I agree.  We can bring this up in the next call, I think its likely that aws will propose hosting it.  @d-nishi I'm guessing you've thought about this?

**Comment by errordeveloper** [comment]
Related #119

**Comment by christopherhein** [comment]
This has been changed in the 0.4.0 release
/close
