### ISSUE TITLE
Permission denied on cert.pem at startup.

### ISSUE THREAD

**Issue by pms1969** [kubernetes-sigs/aws-iam-authenticator#111]
Hi, I'm trying to get authenticator working on a test cluster, and when I deploy it, I get:
```log
level=fatal msg="could not load/generate a certificate" error="open /var/heptio-authenticator-aws/cert.pem: permission denied"
```

The daemonset is pretty much the example.yaml here: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/example.yaml ; with the exception that it's v.0.3.0-alpine

Any idea what I might have screwed up?

**Comment by arjuncomar** [comment]
I see the same thing unless I install a hook to change permissions on the pem files. It makes sense because both files seem to be installed with read permissions only for root. Changing the pem permissions to `640` ought to do the trick.

**Comment by pms1969** [comment]
@nckturner As yet unresolved, but I now know more about what I'm doing.  Happy to close this off.  I think I'll have it fixed soon.

@arjuncomar Thanks.  Might need to look at that when I've sorted out the directory permissions issue. :/

**Comment by arjuncomar** [comment]
@pms1969 It turned out to be an issue at the interface of kops and aws-iam-authenticator for me. kops writes those files out as 600 and root-owned by the container runs as uid 10000. I'll open a PR on the kops side and see if they have an issue with changing the permissions to 644.

**Comment by pms1969** [comment]
@arjuncomar I'm not using kops, but that's exactly the problem.  When I got on the controllers and fixed up the permissions, it worked fine.  Just have to figure out how to make that work with my setup now. :)

**Comment by pms1969** [comment]
As far as I recall, it was a permissions problem on the files (owned by root?)
