### ISSUE TITLE
release in this repo using new binary name

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes-sigs/aws-iam-authenticator#119]
Right now the latest release is 0.3.0 and there binaries are still called `heptio-authenticator-aws`. It seems like there should be a release in the new repo.

**Comment by errordeveloper** [comment]
@christopherhein @jicowan @nckturner is anything blocking this?

**Comment by nckturner** [comment]
Just creating the docker image repositories, which I haven't gotten to yet, but should have time today.

**Comment by errordeveloper** [comment]
Is the code in master ready to be released? Would it be a 0.4.0 or 0.3.1?

**Comment by errordeveloper** [comment]
Any updates on this? If this is not going to happen too soon, could we consider updating release artefacts for 0.3.0?

**Comment by errordeveloper** [comment]
Is there going to be a release any time soon? If not, how do I know which revision should I track?

**Comment by rifelpet** [comment]
Agreed.

@nckturner, can 0.4.0 be released sometime soon? It's been almost 6 months since 0.4.0-alpha.1 and 10 months since 0.3.0.

It would be great to get a stable release since the project rename 9 months ago.

**Comment by christopherhein** [comment]
As of today 0.4.0 has been released under the EKS ECR account. https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.4.0

/close
