### ISSUE TITLE
Prompted for username/password using 0.3.0

### ISSUE THREAD

**Issue by christensen143** [kubernetes-sigs/aws-iam-authenticator#142]
I have changed my config file over to use the new exec style from the haawrapper. When I attempt to run kubectl for anything I am prompted for a username and password. If I switch back to the haawrapper I don't have the issue. I am running Ubuntu Linux 18.04. Any ideas? Thanks.

**Comment by christopherhein** [comment]
What `kubectl version` do you have @christensen143 ? You must be running at least the 1.10 version.
