### ISSUE TITLE
Use tide for PR merging

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-sigs/aws-iam-authenticator#145]
This is a [SIG repository](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#sig-repositories).  As such, it [needs to use the same merge automation we use on the rest of the project](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-new-repositories)

I have a PR open to address this, I'd like an /lgtm from someone here, ref: https://github.com/kubernetes/test-infra/pull/9304

Alternatively, if I hear no objections by 3pm PT Tue 2018-09-11 I'll merge the PR

**Comment by nckturner** [comment]
Done, thanks!

**Comment by mattlandis** [comment]
Done.  Looking forward to letting tide  do more work for me!
