### ISSUE TITLE
Following instructions for Kops creates unreadable host directory (permissions)

### ISSUE THREAD

**Issue by xrl** [kubernetes-sigs/aws-iam-authenticator#147]
I am installing aws-iam-authenticator with a Kops-managed cluster. I have the systemd unit running on masters and they are successfully copying down the aws-iam-authenticator secrets and filling the proper locations on the master's host filesystem.

The problem is those files are written as root files and the aws-iam-authenticator runs as a non-root user. Is it better to run the container as root or to change the permissions of the written files?

```
# docker logs k8s_aws-iam-authenticator_aws-iam-authenticator-rz4fk_kube-system_785a0080-b8f1-11e8-9b5d-1664c98cb03e_613
time="2018-09-17T18:06:30Z" level=info msg="mapping IAM role" groups="[system:masters]" role="arn:aws:iam::000000000000:role/KubernetesAdmin" username=kubernetes-admin
time="2018-09-17T18:06:30Z" level=info msg="mapping IAM role" groups="[system:bootstrappers aws:instances]" role="arn:aws:iam::000000000000:role/KubernetesNode" username="aws:{{AccountID}}:instance:{{SessionName}}"
time="2018-09-17T18:06:30Z" level=info msg="mapping IAM role" groups="[system:masters]" role="arn:aws:iam::000000000000:role/KubernetesAdmin" username="admin:{{SessionName}}"
time="2018-09-17T18:06:30Z" level=info msg="mapping IAM user" groups="[system:masters]" user="arn:aws:iam::000000000000:user/Alice" username=alice
time="2018-09-17T18:06:30Z" level=fatal msg="could not load/generate a certificate" error="open /var/aws-iam-authenticator/key.pem: permission denied"
```

**Comment by sunfuze** [comment]
I have got permission when wrote config to file `kubeconfig.yaml`
```
time="2018-11-08T06:45:44Z" level=info msg="loaded existing keypair" certPath=/var/aws-iam-authenticator/cert.pem keyPath=/var/aws-iam-authenticator/key.pem
time="2018-11-08T06:45:44Z" level=info msg="writing webhook kubeconfig file" kubeconfigPath=/etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml
time="2018-11-08T06:45:44Z" level=fatal msg="could not write kubeconfig" error="open /etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml: permission denied" kubeconfigPath=/etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml
```

**Comment by grockeek** [comment]
A little recap' about my configuration so far : 

**aws-region** : `eu-west-3`
**kops version** : `Version 1.10.0 (git-8b52ea6d1)`
**kubectl version** : `Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`

<br/>

I have a similar error as @xrl deploying the `ConfigMap` and `DaemonSet` (through helm).
Here is what I obtain in my logs (role and group name have been sanitized) : 


`my_awesome_shell$> kubectl logs aws-iam-authenticator-klrdc -n kube-system` 
```
time="2018-11-13T09:56:14Z" level=info msg="mapping IAM role" groups="[system:masters]" role="arn:aws:iam::123456789000:role/mygroup" username=kubernetes-admin
time="2018-11-13T09:56:14Z" level=info msg="mapping IAM role" groups="[system:bootstrappers aws:instances]" role="arn:aws:iam::000011112222:role/masters.mycluster" username="aws:000011112222:instance:i-xxxxxxxxxxxxxxxxx"
time="2018-11-13T09:56:14Z" level=info msg="mapping IAM role" groups="[system:bootstrappers aws:instances]" role="arn:aws:iam::000011112222:role/masters.mycluster" username="aws:000011112222:instance:i-xxxxxxxxxxxxxxxxx"
time="2018-11-13T09:56:18Z" level=info msg="generated a new private key and certificate" certBytes=811 keyBytes=1191
time="2018-11-13T09:56:18Z" level=info msg="saving new key and certificate" certPath=/var/aws-iam-authenticator/cert.pem keyPath=/var/aws-iam-authenticator/key.pem
time="2018-11-13T09:56:18Z" level=fatal msg="could not load/generate a certificate" error="open /var/aws-iam-authenticator/cert.pem: permission denied"
```

<br/>

- My group `arn:aws:iam::123456789000:role/mygroup"` exists and is valid (a root account).
- My role `arn:aws:iam::000011112222:role/masters.mycluster` exists an is valid (created on cluster deployment trough `additionalPolicies: master`)
- EC2 instance `i-xxxxxxxxxxxxxxxxx` in `000011112222` account is correctly running.

**Comment by grockeek** [comment]
An interesting point, before kops `1.1.10` (stable), user creation brings some problem (uid used inside container can not match `aws-iam-authenticator`, used for certificate generation).

If you want to understand installation behavior, check [Dockerfile.scratch](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/Dockerfile.scratch) (or another dockerfile container).

If you want to have further explanation about code correction, check PR [#5412](https://github.com/kubernetes/kops/pull/5412) and [#5424](https://github.com/kubernetes/kops/pull/5424).

I am trying to make my container deployment with kops version `1.11.0-alpha.1`

**Comment by f-ld** [comment]
Same for me on my old 1.14 kops managed kubernetes cluster:
```
time="2020-08-05T08:28:02Z" level=info msg="generated a new private key and certificate" certBytes=810 keyBytes=1192
time="2020-08-05T08:28:02Z" level=info msg="saving new key and certificate" certPath=/var/aws-iam-authenticator/cert.pem keyPath=/var/aws-iam-authenticator/key.pem
time="2020-08-05T08:28:02Z" level=fatal msg="could not load/generate a certificate" error="open /var/aws-iam-authenticator/cert.pem: permission denied"
```
with `gcr.io/heptio-images/authenticator:v0.3.0`.

And the solution I opted for is add a hook to the my kops cluster config:
```
+  hooks:
+  - name: kops-hook-aws-iam-authenticator-config.service
+    before:
+      - kubelet.service
+    roles: [Master]
+    manifest: |
+      [Unit]
+      Description=Create and set permissions of directories required by aws-iam-authenticator
+      [Service]
+      Type=oneshot
+      ExecStart=mkdir -p /srv/kubernetes/aws-iam-authenticator/ && chmod a+w /srv/kubernetes/aws-iam-authenticator/
```
The replace / update / rolling update of master nodes and then it works.
In case that helps someone.
