### ISSUE TITLE
Long run of "kubectl run" does not refresh IAM token

### ISSUE THREAD

**Issue by adubkov** [kubernetes-sigs/aws-iam-authenticator#148]
This is issue more related to `kubectl`, but it make sense have record here too as it impact EKS.

Related kubectl issue: https://github.com/kubernetes/kubectl/issues/534

Problem is when I'm running container with `--stdin=true` on EKS cluster for ~20min, container app complete successful, but `kubectl` return an error:
```
$ time kubectl run --rm -i sleep --restart=Never --image=ubuntu:precise -- sleep 999
If you don't see a command prompt, try pressing enter.
pod "sleep" deleted
error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))

real	16m41.928s
user	0m0.332s
sys	0m0.125s
```

It seems that `kubectl run` does internally calls `get pods` and it doesn't refresh IAM token.

**Comment by mattlandis** [comment]
#160 should solve this
