### ISSUE TITLE
error: the server doesn't have a resource type "svc"

### ISSUE THREAD

**Issue by laszlocsontos** [kubernetes-sigs/aws-iam-authenticator#157]
**Steps taken**

1) Created an role as per https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html#eks-prereqs
2) Created a K8S cluster as per https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html#eks-create-cluster
3) Created an IAM user with programmatic access with the following permissions

- AmazonEKSClusterPolicy
- AmazonEKSWorkerNodePolicy
- AmazonEKSServicePolicy
- AmazonEKS_CNI_Policy
- AmazonEC2ReadOnlyAccess

Note: the original IAM user we had in `.aws/credentials` used AmazonEC2ReadOnlyAccess.
I added that in order not to break existing scripts.

4) Upgraded AWS CLI

```
% aws --version
aws-cli/1.16.30 Python/2.7.14 Linux/4.14.72-68.55.amzn1.x86_64 botocore/1.12.20
```

5) Installed kubectl as per https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html#eks-configure-kubectl

```
% kubectl version --short --client
Client Version: v1.10.3
```

6) Installed aws-iam-authenticator

7) Generated kubeconfig

```
% aws sts get-caller-identity
XXXXXXXXX	arn:aws:iam::XXXXXXXXX:user/bastion	XXXXXXXXXXXXXXXXXXX

% aws eks update-kubeconfig --name test
Updated context arn:aws:eks:us-east-1:XXXXXXXXX:cluster/test in /home/ec2-user/.kube/config

% kubectl get svc
error: the server doesn't have a resource type "svc"
```

**Debugging**

1) Fetch token

```
% aws-iam-authenticator token -i wizenoze-test 
{
   "kind":"ExecCredential",
   "apiVersion":"client.authentication.k8s.io/v1alpha1",
   "spec":{

   },
   "status":{
      "token":"k8s-aws-v1.XXX"
   }
}
```

2) Verify token

```
% aws-iam-authenticator verify -i test -t k8s-aws-v1.XXX

&{ARN:arn:aws:iam::XXXXXXXXX:user/bastion CanonicalARN:arn:aws:iam::XXXXXXXXX:user/bastion AccountID:XXXXXXXXX UserID:XXXXXXXXXXXXXXXXXXX SessionName:}
```

Could you please help me in finding out what's wrong?

Thanks,
László

**Comment by weotch** [comment]
I was experiencing this until I opened a new tab in Terminal

**Comment by Samze** [comment]
We are also seeing this exact problem. 

We additionally assumed the role we created for our EKS cluster using
```
aws eks update-kubeconfig --name eksgism --role-arn arn:aws:iam::XXXXX:role/eksgism-role
```

We too can seemingly successfully use the aws-iam-authenticator
```
aws-iam-authenticator token -i eksgism -r arn:aws:iam::XXXXX:role/eksgism-role
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"token":"k8s-aws-v1.XXXXX}

aws-iam-authenticator verify -i eksgism -t k8s-aws-v1.XXXXX
&{ARN:arn:aws:sts::XXXXX:assumed-role/eksgism-role/XXXXX CanonicalARN:arn:aws:iam::XXXXX:role/eksgism-role AccountID:XXXXX UserID:XXXXX SessionName:XXXXX}
```

...And opening a new tab did not work :( 

Cheers,
Sam & @teddyking

**Comment by nckturner** [comment]
@laszlocsontos Whichever user/role's credentials you were using when you created the EKS cluster are the credentials you should be using when you try `kubectl get svc`.  (In your case, `user/bastion`).  Was this the same user that you used to create the cluster?  The EKS service role has nothing to do with it.

**Comment by nckturner** [comment]
@Samze it appears that your AWS credentials are not accessible to the authenticator binary.  What happens when you run `aws sts get-caller-identity`?

**Comment by KailasJanardhanan** [comment]
I am facing the exact same issue 
aws sts get-caller-identity gives the following
{
    "Account": "XXXXXXXXXXXX",
    "UserId": "YYYYYYYYYYYYYYYYYYY:i-XXXXXXXXXXXXX",
    "Arn": "arn:aws:sts::XXXXXXXXXXXX:assumed-role/<Role Name>/i-<XXXXXXXXXXXXX>"
}

**Comment by mrichman** [comment]
Identical issue here.

**Comment by bestbear** [comment]
I'm facing the exact same problem as well.  Interestingly enough, the token generation works but the verify fails:  aws-iam-authenticator verify -i test -t "k8s-aws-v1.a<REDACTED>MGI3YjY0M2M0YjE1Njk5" 
could not verify token: sts getCallerIdentity failed: error from AWS (expected 200, got 403)

**Comment by narup** [comment]
+1

**Comment by bestbear** [comment]
narup, yes, you might be on to something.  I create the cluster from the GUI using SSO credentials which would have used temporary access/secret keys.  All the kubectl work was done using my permanent access/secret key pair.  I will have to go back and validate this again using only the CLI with my access/secret.

**Comment by pastephens** [comment]
Also seeing this. I created two clusters, one in the console and one from the CLI. The result is the same error. I can fetch and verify my token is my SAML user, which I used to create both clusters.

**Comment by luthes** [comment]
Might you guys be using Terraform at all? I know it's still just an API call for both. I'm seeing this when using Terraform that assumes a role, and regardless of if I assume that role or not, I can't access the control plane.

**Comment by bestbear** [comment]
Negative, I'm not using Terraform for this only the Console and the CLI.

**Comment by Fatxx** [comment]
My problem was related to not having my IAM user keys set as default at `~/.aws/credentials`, I was using the --profile flag to run AWS CLI commands as I normally do but it doesn't seems to work for this case

**Comment by luispabon** [comment]
I'm having the exact same issue. Kubectl logs say

```
I1123 13:09:45.789218   28300 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

**Comment by jaydipdave** [comment]
EKS is a suicide mission by AWS. This Elastic Kube Shit is not working.

1) Created a role
2) Set my user as trusted entities.
3) Assigned a policy to my user so it can assume the role.
4) Created EKS Cluster
5) Installed latest aws*, kubectl
5) `aws eks update-kubeconfig --name xxxxxxxx --role-arn arn:aws:iam::xxxxxxxxx:role/EKS-Manager`
6) `Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}`

All so tried using a readily available EKS-cli docker images, but same error.

Tried curl as well:

```
# TOKEN=$(aws-iam-authenticator token -i shit | jq -r .status.token)
# curl $APISERVER/version --header "Authorization: Bearer $TOKEN" --insecure
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

Try 2:

```
# TOKEN=$(aws-iam-authenticator token -i shit -r arn:aws:iam::xxxxxxxxxxxxx:role/EKS-manager | jq -r .status.token)
# curl $APISERVER/version --header "Authorization: Bearer $TOKEN" --insecure
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
Tried old version:

```
# TOKEN=$(heptio-authenticator-aws token -i shit | jq .status.token)

curl $APISERVER/version --header "Authorization: Bearer $TOKEN" --insecure
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Comment by mrichman** [comment]
@jaydipdave Who are you at the CLI when getting your token (i.e. `aws sts get-caller-identity`)? Is this the same user that created the cluster? I'm at re:Invent right now. Hoping to find some EKS folks to talk to about the user experience here.

**Comment by jaydipdave** [comment]
> @jaydipdave Who are you at the CLI when getting your token (i.e. `aws sts get-caller-identity`)? Is this the same user that created the cluster? I'm at re:Invent right now. Hoping to find some EKS folks to talk to about the user experience here.

Hi @mrichman ,

Thanks for you quick response. I am using a different user at AWS CLI. i.e. "tools".
But EKS-user has a policy to assume the role:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::xxxxxxxxxxxxx:role/*"
        }
    ]
}
```

And in the role, who created the EKS cluster, I set the Trusted Entities.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::xxxxxxxxxxx:user/tools"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

I am assuming the role using "-r arn:aws:iam::xxxxxxxxxxxxx:role/EKS-manager ". 

Should this be sufficient?

**Comment by luthes** [comment]
This really should be sufficient, but I don't think it is, and I think it's the problem that we're running into. Using an assumed role hasn't worked for me at all when creating a cluster, I've tried this a bunch of different ways. The only way I can do it is by using a logged in user (which uses an assumed role through SAML auth) Maybe we're all doing something wrong, but I haven't been able to figure it out.

And a little off topic, adding other users/roles at creation is a huge oversight by AWS, if one is added at creation, I can't see why they woudn't have thought to give us the ability to add more.

**Comment by mrichman** [comment]
I’m here at reinvent trying to get an audience with anyone on the EKS team who can help.

**Comment by bestbear** [comment]
I think the nut of the problem has do to with the initial EKS cluster creation and then the following commands via kubectl.  My hypothesis is that the initial EKS cluster setup is done via the console and then the subsequent provisioning via the kubeclt on the cli breaks the aws-iam-authenticator model because the initial cluster creation stores data in the master node that is hidden.  I will attempt to prove this theory as soon as I get a moment.  At the Reinvent conference in Vegas.

Regards

Mark Cwetna
Slalom

**Comment by yazfaz** [comment]
### **Possible solution if you created the cluster in the UI**

If you created the cluster in the UI, the AWS ```root``` user created the cluster. According to the docs, "When an Amazon EKS cluster is created, the IAM entity (user or role) that creates the cluster is added to the Kubernetes RBAC authorization table as the administrator (with system:master) permissions. Initially, only that IAM user can make calls to the Kubernetes API server using kubectl. "

You'll need to first login to the AWS CLI as the ```root``` user in order to update the permissions of the IAM user you want to have access to the cluster.

1. You'll need to get an  [access key for the root user](https://docs.aws.amazon.com/en_us/IAM/latest/UserGuide/id_root-user.html#id_root-user_manage_add-key) and put this info in ```.aws/credentials``` under the default user. You can do this using the command ```aws configure```

     Now ```kubectl get svc``` works, since you're logged in as the root user that initially created the cluster.

2. [Apply the aws-auth ConfigMap to the cluster](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html). Follow step 2 from these docs, using the ```NodeInstanceRole``` value you got as the ```Output``` from [Step 3: Launch and Configure Amazon EKS Worker Nodes](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html#eks-launch-workers)

3. [To add a non-root IAM user or role to an Amazon EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html), follow step 3 from these docs.
Edit the ```configmap/aws-auth``` and add other users that need ```kubectl``` access in the ```mapUsers``` section.

4. Run ```aws configure``` again and add the access key info from your non-root user.

Now you can access your cluster from the AWS CLI and using kubectl!

**Comment by jaydipdave** [comment]
Getting the root user credentials is not possible for everyone. In my case, I am using centrally managed role by the organization. I have admin access but don't have root credentials.

**Comment by yazfaz** [comment]
Are you able to [get the Access Key ID and Secret Access Key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for the role you were logged in as when you created the cluster? (Or have an admin role get this for you, if you don't the permissions to do this). And then put that info in `.aws/credentials` and follow the steps above?

**Comment by bestbear** [comment]
Root credentials are taboo.

This tool does not account for the use-case of SAML providers.  The STS AssumeRole always uses temporary keys.  If the master is looking at the temporary keys that is broken.  The keys expire in 60 minutes.

Mark Cwetna
•••sent from my iPhone•••

________________________________

**Comment by GeoffMillerAZ** [comment]
I usually use inter-account role assumption and terraform for creation. After reading above, I decided to do a terraform destroy on my eks master. Then I used the CLI to create it manually and I planned on just doing an import into terraform later. Before I used the CLI to create the new master, I created an IAM user just for the purpose of setting up this master and managing user access. I planned on deleting this IAM user later. But even with this IAM user, I am getting the exact same problem.

```
[staging_ekscreator]
aws_access_key_id=xxx
aws_secret_access_key=xyz
```

```
aws --profile=staging_ekscreator eks create-cluster --cli-input-json file://eks.json
aws --profile=staging_ekscreator eks update-kubeconfig --name my-eks
kubectl get svc --v=10
I1130 15:23:45.150251   17868 loader.go:359] Config loaded from file /Users/gmiller/.kube/config
I1130 15:23:45.151062   17868 loader.go:359] Config loaded from file /Users/gmiller/.kube/config
I1130 15:23:45.151634   17868 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.12.3 (darwin/amd64) kubernetes/xxx" -H "Accept: application/json, */*" 'https://xxx.sk1.us-west-2.eks.amazonaws.com/api?timeout=32s'
I1130 15:23:45.929480   17868 round_trippers.go:405] GET https://xxx.sk1.us-west-2.eks.amazonaws.com/api?timeout=32s 401 Unauthorized in 777 milliseconds
I1130 15:23:45.929518   17868 round_trippers.go:411] Response Headers:
I1130 15:23:45.929525   17868 round_trippers.go:414]     Audit-Id: xxx
I1130 15:23:45.929530   17868 round_trippers.go:414]     Content-Type: application/json
I1130 15:23:45.929535   17868 round_trippers.go:414]     Content-Length: 129
I1130 15:23:45.929542   17868 round_trippers.go:414]     Date: Fri, 30 Nov 2018 22:23:45 GMT
I1130 15:23:45.931723   17868 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I1130 15:23:45.933017   17868 cached_discovery.go:111] skipped caching discovery info due to Unauthorized
F1130 15:23:46.625767   17868 helpers.go:119] error: the server doesn't have a resource type "svc"
```

**Comment by GeoffMillerAZ** [comment]
## update:

https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html
```
apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        # - "-r"
        # - "<role-arn>"
      env:
        - name: AWS_PROFILE
          value: "staging_ekscreator"
```
adding this:
```
      env:
        - name: AWS_PROFILE
          value: "staging_ekscreator"
```
fixed my issue. So maybe on cluster creation you can just use a manually created IAM and then import it into terraform after you use this user to setup your user permissions. Then you can just delete this IAM user to keep your cloud tidy and secure. I'm trying that next.

**Comment by orangewise** [comment]
It works for me now. I had to set the aws credentials in another session (tab) than the one that is using kubectl. Thanks @weotch.

**Comment by pkelleratwork** [comment]
im running into this exact same thing trying to deploy from circleci to an eks cluster. horrible experience.

**Comment by jpatters** [comment]
I've tried about 15 times in the last 24 hours to create a cluster that I can actually access. 
I've tried from the console, from the cli, with the terraform module. 
I've double and triple checked that the IAM credentials I created it with are the same as the ones I am trying to connect with. 
I've tried using a role, using root credentials, using an IAM user. I've tried specifying a profile or even the exact keys when using `aws-iam-authenticator`. 
I have followed the official amazon getting started guide, the terraform getting started guide, and another random one I found.
Nothing I have done has resulted in a cluster that I can actually authenticate with or that nodes can even connect to. The authenticator can create a token but cannot verify it.

```
$ aws-iam-authenticator verify -i <clusterid> -t <token>
could not verify token: sts getCallerIdentity failed: error from AWS (expected 200, got 403)
```

Is EKS just broken?

**Comment by mrichman** [comment]
@jpatters This has happened to me before too. You're not using Cloud9 by chance are you?

Also, what's in your `~/.aws/credentials` (**don't post it here**) just curious if you have multiple profiles, or anything in there **other** than just `aws_access_key_id` and `aws_secret_access_key`. I once had `aws_session_token=` (no value) which screwed me up like you're seeing.

What's the output from `aws sts get-caller-identity`? Does it match the ID in your credentials?

**Comment by jpatters** [comment]
@mrichman I am not using cloud9. However I did just get this to work by explicitly exporting aws key and secret
```
export AWS_ACCESS_KEY_ID=key
export AWS_SECRET_ACCESS_KEY=secret
```
(I know I said I tried this in my comment above but I must not have)

I do have multiple profiles in `~/.aws/credentials` but I have verified that `aws sts get-caller-identity` returns the correct one. 

At the moment, it seems to me like `aws-iam-authenticator` is not properly reading `~/.aws/credentials` or maybe `~/.aws/config`

It was working on a test cluster just now. I am now launching my intended cluster via terraform and I will report back what I find.

**Comment by jpatters** [comment]
The only way it is working for me is if I explicitly export the credentials. It seems to be caused by the authenticator not reading `~/.aws/credentials` properly (or not it at all)

**Comment by reachhsubbu** [comment]
Yes. second it. It works only if I explicitly export the credentials.

**Comment by GeoffMillerAZ** [comment]
I spoke to a gentleman at the AWS EKS booth at Kubecon. I explained this problem and how I typically use credentials that are temporary from STS due to MFA and role assumption. He said they are getting a lot of complaints on this problem and that they are trying to come up with a good solution. I shared that what I had done was to make an IAM user in that specific account for the purpose of account creation and that I intended to delete the user after I setup permissions the way I needed on RBAC. He said that is a good solution except to not delete the account but to keep it as a break-glass account in case problems arose. 

He also mentioned they _may_ be working on a solution to expose master logs to you so you can see and troubleshoot without as much guessing.

**Comment by nakulpathak3** [comment]
Are there any other workarounds/fixes for this? I tried explicitly exporting `AWS_ACCESS_KEY_ID` and `AWS_ACCESS_SECRET_KEY` and that did not work. Also tried adding
```
env:
        - name: AWS_PROFILE
          value: "staging_ekscreator"
```
and that failed on cluster create too. The error I'm getting is `ERROR:root:exec: process returned 1. could not get token: AccessDenied: Access denied
	status code: 403, request id: e63b2a9f-03e2-11e9-9cea-e510a9909b67` and I'm using the Kubernetes Python Client not `kubectl`.

**Comment by falfaro** [comment]
Is this a problem with `aws-iam-authenticator` or not? Exporting the credentials is a valid workaround but very ugly.

**Comment by schumacher-m** [comment]
I followed https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
to add ARN of my colleagues who wants to manage the cluster:

`kubectl edit -n kube-system configmap/aws-auth`

**Comment by joshuabaird** [comment]
Like many others here, we use STS and assumed roles with profiles to access our AWS account(s).  We encountered the same problem(s) that others here have.  Thanks to @GeoffMillerAZ, I was able to get this working by doing the following:

* Provision a new EKS cluster using `aws eks create-cluster` and specifying the correct profile using `--profile blah`
* Run `aws eks update-kubeconfig --name clustername --profile blah` to create a shell `~/.kube/config`
* Modify `~/.kube/config` and add:

```
      env:
      - name: AWS_PROFILE
        value: "blah"
```

After this, I was able to run `kubectl get svc':

```
➜  kubectl get svc
Assume Role MFA token code: 123456
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.20.0.1   <none>        443/TCP   13m
```

This is mostly documented here:  https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html.

I would have to agree with others that the documentation (especially the "Getting Started" documentation) is not clear.  Using STS with assumed roles is a very common pattern for many customers, and this should be addressed more eloquently.

**Comment by falfaro** [comment]
Thanks for the investigation. Do I understand that this is a problem with EKS and not with BKPR?

**Comment by falfaro** [comment]
Oh, and BTW, another alternative that I believe can work is exporting the environment variable AWS_PROFILE instead of using the `--profile` flags and modifying the Kube configuration.

**Comment by lliknart** [comment]
We had the same issue with EKS cluster.

We use Jenkins to deploy. After many errors and tries, we verify the token with the following command
`aws-iam-authenticator verify -i cluster_name -t token_id` 
it appears that the token has been generated for an IAM user than the expected role

We check the env variables. It appears that the following environment variables are set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. 
Those are injected by Jenkins (with the aws-credentials plugin).

So, the AWS profile was good, but it used env variables to generate the token.

By unsetting this env variables the token is well generated and we can now request the EKS cluster

**Comment by SarasaGunawardhana** [comment]
I could not solve this issue by creating a cluster on AWS EKS GUI. I tried eksctl to create cluster and it worked.
