### ISSUE TITLE
aws-iam-authenticator without Amazon EKS

### ISSUE THREAD

**Issue by astronauft** [kubernetes-sigs/aws-iam-authenticator#158]
Hi guys, 
Can I use aws-iam-authenticator if I do not use Amazon Managed Kuberenetes Services (EKS).
I will be grateful if you can send me this information.

**Comment by marjamis** [comment]
I was able to get it running on my manually created testing cluster, i.e. not EKS, by following the README page here:
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md

From memory I didn't have to change anything and was largely a straight forward process.

**Comment by nckturner** [comment]
Yeah, it should work in a non-EKS cluster, following the README linked by @marjamis.  Let us know if you run into any issues.
