### ISSUE TITLE
How to update user's permissions immediately without manually delete pods

### ISSUE THREAD

**Issue by chrisduong** [kubernetes-sigs/aws-iam-authenticator#175]
Hi,

After all pods are running, if I updated the Configmap with new user. It won't take effect immediately. I have to manual delete pods, so the server will restart with the new configurations.

I don't know if this is the only way to force update. Is there any other way to  update user's permissions immediately. Thanks.

**Comment by holyjak** [comment]
Hi @chrisduong , do you know what pods have to be deleted for the config change to take effect? Not all?

**Comment by nckturner** [comment]
Currently the authenticator server has to be restarted in order for it to reload the configuration.  @christopherhein is working on a change that will allow the configmap information to be stored in custom resources and watched without restart.

**Comment by joekohlsdorf** [comment]
@christopherhein Any update on this? Also I would like to add that custom resources are overkill.
You can just periodically check if the configmap has changed. Examples can be found in coredns, ingress-nginx or here: https://github.com/jimmidyson/configmap-reload

**Comment by christopherhein** [comment]
Thanks for the feedback, this pr #116 was already merged into master, but I’d love to understand why you think it’s overkill? Given that this a mission critical component when is currently defined by a ConfigMap with a stringified yaml block it has a high risk for users misconfiguring it and breaking authentication but something as simple as a missed space, or an incorrect copy and paste. Being able to put this out of ConfigMaps gives us the ability to validate and properly mutate these values instead doing everything in-memory. It also gives us the ability to use the informer caches can make the controller more efficient vs marshaling and unmarshalling a stringifed yaml block.
