### ISSUE TITLE
EKS Authenticaton From Outside Cluster

### ISSUE THREAD

**Issue by svozza** [kubernetes-sigs/aws-iam-authenticator#202]
I have a use case where I need to interact with an EKS cluster from a lambda function and encountered an issue that took extended debugging before I figured out what was going on. The issue is around creating the bearer token that the `aws-iam-authenticator`. 

Here's some simple Python code to create the token.

```python
REGION = 'eu-west-1'

def get_bearer_token(cluster, region):
    # ...

    signer = RequestSigner(...)

    params = {
        'method': 'GET',
        'url': 'https://sts.{}.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15'.format(REGION),
        'body': {},
        'headers': {
            'x-k8s-aws-id': cluster
        },
        'context': {}
    }

    signed_url = signer.generate_presigned_url(
        params,
        region_name=REGION,
        expires_in=60,
        operation_name=''
    )

    base64_url = base64.urlsafe_b64encode(signed_url.encode('utf-8')).decode('utf-8')

    return 'k8s-aws-v1.' + base64_url 
```

The issue I encountered was that if the base64 encoded string has any padding (ie., either `=` or `==`) then if you pass the token created with the above function it fails. However if I remove the padding it works:

```python
return 'k8s-aws-v1.' + re.sub(r'=*', '', base64_url)
```

I'm not sure if this is a bug but it is very surprising and took me days to figure so at the very least it should be documented. I'm more than happy to do a pull request to add that documentation and in fact, I found there was very little official documentation on how this Bearer token was created at all (I had to piece it together from several blog posts) so I'd be happy to add that to the documentation as well.

**Comment by markthebault** [comment]
@svozza You are a genius !!! I spend 3 days trying to find where did the problem come from!

**Comment by svozza** [comment]
Haha. Yeah, I wasted nearly a week on this! The most annoying thing was that it would suddenly start working and it was only afterwards that I realised it was because randomly the string would not have the padding because `generate_presigned_url` is not a pure function.

**Comment by nckturner** [comment]
Thanks for documenting this!  It is due to the fact that RawURLEncoding which we use to generate tokens explicitly omits padding to avoid any `=` characters in order to create a string safe to use in URLs.

`var RawURLEncoding = URLEncoding.WithPadding(NoPadding)`

A documentation PR would be welcome.

Reference:
https://github.com/golang/go/blob/go1.12.1/src/encoding/base64/base64.go#L110:5
