### ISSUE TITLE
can I use aws-iam-authenticator with kubernetes on-premise

### ISSUE THREAD

**Issue by benishak** [kubernetes-sigs/aws-iam-authenticator#203]
Hi

We have 2 Kubernetes clusters 
- On AWS : we use EKS
- On Premise : vanilla Kubernetes 1.11

We manage our users with AWS IAM and we want to unify how user access kubernetes on AWS and on-prem via kubectl / api.

Can I use aws-iam-authenticator with my on-prem kubernetes cluster?

this is only about users interacting with kubernetes cluster via kubectl not about how nodes access the cluster

**Comment by christopherhein** [comment]
Yes, you can do this. You will need to configure the API Server that to pass authentication through the webhook for your on-premises cluster. The server uses the AWS API by only completing the http request that is base64 encoded as the token.
