### ISSUE TITLE
iam authenticator with latest aws-sdk-go since proxies does not work

### ISSUE THREAD

**Issue by badaldavda8** [kubernetes-sigs/aws-iam-authenticator#207]
Hi,

This is Badal from AWS Premium Support. One of the customers is having issues with using aws-iam-authenticator.

"""
aws-iam-authenticator currently uses a version of aws-sdk-go that doesn't work with proxies when using custom CA bundles via the AWS_CA_BUNDLE environment variable. This prevents us using IAM authentication with kubectl because our corporate man-in-the-middle proxies require us to set a custom CA bundle.

We believe that using a more recent version of aws-sdk-go will fix this (assuming it includes https://github.com/aws/aws-sdk-go/pull/2343 ), but until then, the official release is broken.
"""

Can you confirm if this is the issue? Is there any way to work-around this issue?

Awaiting your response.

**Comment by badaldavda8** [comment]
Any update on this?

**Comment by jfautley** [comment]
FYI we're having the same issue as above (I'll be raising this with our Enterprise TAM as well), but it looks like a workaround is to create a wrapper script:

```$ cat aws-iam-auth-wrapper
#!/bin/bash

unset AWS_CA_BUNDLE
exec /usr/local/bin/aws-iam-authenticator "$@"
```

... and then replace the binary in `~/.kube/config` with this wrapper script.

NB: Our interception CA is in the system certificate store, YMMV, etc.
