### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes-sigs/aws-iam-authenticator#22]
First of all, thanks for the amazing project!

I'm looking at the code, and super pleased to see you've used viper/cobra. I'd like to add configuration so that I can specify things like my role and clusterid in a config file if I only have a single cluster or role. That way, I don't need to specify them every time on the command line. That way this:

```
heptio-authenticator-aws token -i <id> -r '<role_arn>'
```

Can be simplified to:

```
heptio-authenticator-aws 
```

**Comment by mumoshu** [comment]
Hi @jaxxstorm, I'm also interested in this, too!

Not sure if you were aware of the `--config`  flag at the time of writing but anyway -

Would it help if we just had a convention that e.g. `./authenticator.yaml` is considered as the default value for the flag?

**Comment by mumoshu** [comment]
Just for clarification, I know that we can of course do `alias au='authenticator --config authenticator.yaml'` or even `alias au='authenticator --config $(upfind -name authenticator.yaml)'` today 😃 

However, having a sane default is still useful for communication. Without a default, we have to figure out the location of the config file per project.

**Comment by christopherhein** [comment]
@mumoshu @jaxxstorm do you think this is still important?
