### ISSUE TITLE
Update authenticator server side to be less strict on base64 padding

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-iam-authenticator#227]
Ref: https://github.com/aws/aws-cli/pull/4146

**Comment by micahhausler** [comment]
In [`tokenVerifier.Verify()`](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/7421a91/pkg/token/token.go#L374) we should [try several encodings](https://github.com/micahhausler/jwtdecode/blob/master/pkg/jwt.go#L90-L111) before giving up
