### ISSUE TITLE
Compile instructions?

### ISSUE THREAD

**Issue by mlintonford** [kubernetes-sigs/aws-iam-authenticator#232]
Can anyone add steps to recompile this?

I am unable to download exe files due to company proxies, but have complete development environment, including golang etc

**Comment by nckturner** [comment]
In general you can just run make, given that you have the `goreleaser` binary.  I'd like to remove that as a dependency or vendor it, though.  Otherwise, you can do something like this: 
```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o _output/linux/amd64/aws-iam-authenticator -ldflags ${ld_flags} github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
```
