### ISSUE TITLE
AWS Cognito?

### ISSUE THREAD

**Issue by wolfeidau** [kubernetes-sigs/aws-iam-authenticator#24]
Did you ever consider just using the Cognito API to provision users, and map them to roles?

AWS Cognito now even supports OAuth2 endpoints and role mappings.

Eager to hear your thoughts on this?

Auth flow is linked below.

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html

**Comment by mumoshu** [comment]
Hi @wolfeidau! I'm interested in the integration, but how would the expected user story for this look like?

Do you intend to initiate an auth flow from within e.g. your own web app backed by your own user pool, and somehow passing the temp AWS credentials obtained on completion to heptio/authenticator?

If that's the case, how it compares with just creating a regular IAM user in your AWS account in context of authn/authz to K8S API?

Thx!
