### ISSUE TITLE
Unable to pull oci image from registry for v0.4

### ISSUE THREAD

**Issue by hyperbolic2346** [kubernetes-sigs/aws-iam-authenticator#243]
`$ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.4.0
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-iam-authenticator/manifests/v0.4.0: no basic auth credentials`

Is this a public image or is it supposed to be locked behind auth? I don't see any auth added in the yaml for this registry, but maybe I missed something.

**Comment by hyperbolic2346** [comment]
For anyone else hitting this. I just stumbled across the following in the release notes:

```
Note: You must log in with the registry ID and your role must have the necessary ECR privileges:

$(aws ecr get-login --no-include-email --region us-west-2 --registry-ids 602401143452)
```

This bug should be about the documentation for how to use it not talking about the registry credentials.

**Comment by leosunmo** [comment]
This is quite annoying and I don't see why we need to authenticate to pull this image, especially since it's a critical piece required early in the cluster lifetime. Is there a reason we have to log in to is this a mistake in the latest release?
