### ISSUE TITLE
Add flag for configurable backends

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-iam-authenticator#247]
There are three methods to configure mappings: 
1. static file https://github.com/kubernetes-sigs/aws-iam-authenticator#full-configuration-format
2. CRD's https://github.com/kubernetes-sigs/aws-iam-authenticator#configure-iamidentitymapping-custom-resource-definitions 
3. configmap (EKS-only and not open source) https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html 

EKS would like to open source the configmap method and leave the door open for other options, such as an EKS API. To that end, a new "--backend-mode" flag should be added to allow users to configure which methods to enable and their order of precedence.

**Comment by dnascimento** [comment]
Will EKS support CRD in the near future?
