### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by cdobbyn** [kubernetes-sigs/aws-iam-authenticator#258]
This is the same request as what was found in #63 however in that issue the "X-Amz-Expires" was incorrectly identified as having a hard set maximum of 600s (15 minutes). This limit is based on what is set within the AWS console. See the v4 reference here:
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html#x-amz-expires

The problem is we are assuming this "presignedURLExpiration" is static at 15 minutes and then basing token expiration on 1 minute less than this value:
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/ed1ce8bd6af7e648f2f12bdce0c725a084fc7db7/pkg/token/token.go#L77

This presignedURLExpiration should be both user configurable as something like `--session-timeout` in the token command or looked up via the profile configuration value `duration_seconds`. If neither of these is provided, we should only then default to 15 minutes.

If time permits I'll open a PR unless someone else can beat me to it.

**Comment by catalinpan** [comment]
This will be nice to have. In the mean time I've created a little script which takes care of MFA seamlessly as long as there is an yubikey plugged. Might be useful to use it in the mean time so I'll put it [here](https://github.com/cststack/km)

**Comment by nckturner** [comment]
> This is the same request as what was found in #63 however in that issue the "X-Amz-Expires" was incorrectly identified as having a hard set maximum of 600s (15 minutes). 

The link you have provided is specific to S3.  Unfortunately, STS does not support "X-Amz-Expires" and last I spoke to them they don't plan to.
