### ISSUE TITLE
v0.5.0 Release

### ISSUE THREAD

**Issue by nckturner** [kubernetes-sigs/aws-iam-authenticator#274]
Let's plan for the v0.5.0 release.

**Comment by luis-silva** [comment]
Any release would be great. The last one was over 6 months ago and a lot of new stuff has been added to master since then.

**Comment by bneelima84** [comment]
Yes, please plan to release 0.5.0. Waiting for the fixes

**Comment by bneelima84** [comment]
Any update on this please ?

**Comment by jdmulloy** [comment]
Can you please release an update? I need a version of this with the updated SDK to get argocd to auth to other clusters using service account role assumptions as announced here https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/.

**Comment by thefirstofthe300** [comment]
Ditto on getting an update pushed. I'm attempting to use ArgoCD in an EKS cluster and am running into the issue of the AWS IAM authenticator not having support for the AWS_ROLE_ARN env var.
