### ISSUE TITLE
IAM roles with paths are only recognized without the path

### ISSUE THREAD

**Issue by zettatronn** [kubernetes-sigs/aws-iam-authenticator#280]
Reopening closed Issue #153 

Assuming I have the following role ARN:

arn:aws:iam::1234567890:role/iam-ss/some-path/actual-role-name
If I enter this under mapRoles, this will not be recognized. Instead I need to enter:

arn:aws:iam::1234567890:role/actual-role-name

This ticket was closed due to inactivity but this bug is still present. We currently have to use 2 ARNs in all configmaps to work around this issue.

**Comment by nckturner** [comment]
Thanks, I reopened the original issue.
