### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by Am1rr3zA** [kubernetes-sigs/aws-iam-authenticator#281]
I have created a cluster with my user and for some reason, I had to delete that user; now I can not access my EKS cluster? after some investigation and reading issues here I found that I need that user to let other users get access to the EKS cluster is that true?

since I deleted the original users what are my options here?

**Comment by nckturner** [comment]
If you create a new user with the same name, you will be able to access the cluster.  Otherwise, you need to recreate the cluster.

**Comment by Am1rr3zA** [comment]
it's kinda strange, how can we deal in production? if I want to create an EKS cluster and want to leave the company they should keep my user forever?

**Comment by TBeijen** [comment]
You can add users and roles that can access the cluster by editing configmap `kube-system:aws-auth`. Google it, it's in the EKS docs.

**Comment by micahhausler** [comment]
>  if I want to create an EKS cluster and want to leave the company they should keep my user forever?

@Am1rr3zA  The organization can re-create the IAM user or role name (with new AWS credentials) and use that to access your cluster.

If there are any changes you'd like to see to EKS relating to authenticator, feel free to open or +1 an issue or on our [aws/containers-roadmap](https://github.com/aws/containers-roadmap/issues?q=is%3Aissue+is%3Aopen+authenticator+label%3AEKS) project. 

Is there anything else you need for this project?

**Comment by TBeijen** [comment]
Slightly related: Is it possible to see somewhere in the API or console who/what has created a cluster? I might have totally overlooked it but couldn't find that property anywhere.

**Comment by micahhausler** [comment]
@TBeijen Nope. See the above link if you want to +1 a feature request
