### ISSUE TITLE
intermittent "unable to locate credentials" error

### ISSUE THREAD

**Issue by itajaja** [kubernetes-sigs/aws-iam-authenticator#285]
I am (pretty consistently) able to reproduce an issue that is bugging me for some time. here is a minimum reporoduction:

```sh
kubectl run --restart='Never' --rm -it btest --image=ombu/boto3:1.8 -- python -c "import time; time.sleep(0); import boto3; boto3.client('s3').download_file('foo', 'bar', 'baz')"
```

this basically runs an image with bot and tries to download a file. most of the times, I get `botocore.exceptions.NoCredentialsError: Unable to locate credentials`.

Now, if I slightly modify my script to wait before running the s3 command:

```sh
kubectl run --restart='Never' --rm -it btest --image=ombu/boto3:1.8 -- python -c "import time; time.sleep(10); import boto3; boto3.client('s3').download_file('foo', 'bar', 'baz')"
```

most of the times (but not always!) the call succeeds. so, it seems related to some sort of lazy loading of the credentials that are not present when the container starts, or something along these lines.

I am running on EKS, kubernetes version `1.14`. also running calico (not sure if that makes a difference)

Any hints of what might be going on?

**Comment by itajaja** [comment]
👋 ping. myabe this is not the right place?

**Comment by micahhausler** [comment]
Yea, this is unrelated to this project. How are you getting credentials to your pod?

**Comment by itajaja** [comment]
oops. I am not, they are injected there by nature of the pod being on an EC2 instance. but for some imperscrutable reasons, the machinery fails sometimes. I'll close it and do more research on the topic. thanks!

**Comment by shalev123d** [comment]
@itajaja Have you solved the issue? We're encountering the exact same problem
