### ISSUE TITLE
error: You must be logged in to the server (Unauthorized) when running "kubectl tops pods" command

### ISSUE THREAD

**Issue by naveenkumarhm** [kubernetes-sigs/aws-iam-authenticator#289]
I have added new IAM role(ec2admin) to aws-auth(Snippet - A) config maps under groups " - system:masters" and I am able access the cluster and run few kubectl commands, but when I am trying to run kubectl top pods command, I am running into below error, and I was able fix the error by adding username under the mapRoles:
------
error: You must be logged in to the server (Unauthorized)
------

------Snippet -A------
 kubectl get cm/aws-auth -n kube-system -o yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::12345678:role/eksctl-devcluster-nodegroup-devek-NodeInstanceRole-8VGZP6CLR72B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
      rolearn: arn:aws:iam::12345678:role/ec2admin
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-06T16:42:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4074632"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 83435581-30a3-11ea-94a0-0aa06a9369eb
----------- 

1) Why I am unable to run kubectl top pods command and rest of the commands works fine
    --- Cloudwatch Logs
           -- time="2020-02-04T17:13:28Z" level=warning msg="access denied" arn="arn:aws:iam::12345678:role/ec2admin" client="127.0.0.1:44414" error="ARN is not mapped: arn:aws:iam::12345678:role/ec2admin" method=POST path=/authenticate
---------------
2) After adding the username in the mapRoles(snippet -B).

----(snippet - B)-------
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::12345678:role/eksctl-devcluster-nodegroup-devek-NodeInstanceRole-8VGZP6CLR72B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
      rolearn: arn:aws:iam::12345678:role/ec2admin
      username: ec2admin
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-06T16:42:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4074632"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 83435581-30a3-11ea-94a0-0aa06a9369eb
-----

I am able to run kubectl top pods:
kubectl top pods
NAME                                       CPU(cores)   MEMORY(bytes)   
nginx-pod                                  0m           2Mi             
photo-filter-deployment-96c658f7-5vjgn     0m           1Mi             
photo-storage-deployment-97d7c545f-qjd6x   0m           0Mi             
php-apache-84cc7f889b-dnhrm                1m           12Mi            
web-client-597dc8694d-chr6k                0m           0Mi

**Comment by danopia** [comment]
I saw the same thing on EKS 1.14/1.15.

```
$ kubectl get pods
error: You must be logged in to the server (Unauthorized)

$ kubectl edit configmap aws-auth -n kube-system
  (add eg `username: CorpAdmin` to the proper config block)
configmap/aws-auth edited

$ kubectl top pods
NAME                            CPU(cores)   MEMORY(bytes)   
kibana-5ccf5cf64c-ml8rx         3m           127Mi           
kibana-5ccf5cf64c-vghz5         3m           127Mi           
...
```

I suppose some aspect of `top` is specifically checking for non-null usernames. I haven't had the same issue with any other commands in the past year.

I don't think the ticket belongs here, just documenting while I keep looking.

**Comment by calebpalmer** [comment]
I am also experiencing this.

**Comment by lodotek** [comment]
Why was this closed w/o resolution?
