### ISSUE TITLE
 endTime.Sub(startTime).Milliseconds undefined

### ISSUE THREAD

**Issue by absolutarin** [kubernetes-sigs/aws-iam-authenticator#294]
Hello, I'm trying to install "aws-iam-authenticator" on my docker image through a dockerfile but it is failing on the go get .... step. 

My dockerfile has this line for installation and it was working a while ago: 
`RUN go get -u -v sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator` 

Since it run it on verbose mode, I could see where its failing and what packages it gets. The error is here: 

> sigs.k8s.io/aws-iam-authenticator/pkg/mapper/crd
> sigs.k8s.io/aws-iam-authenticator/vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface
> sigs.k8s.io/aws-iam-authenticator/pkg/ec2provider
> src/sigs.k8s.io/aws-iam-authenticator/pkg/ec2provider/ec2provider.go:237:57: endTime.Sub(startTime).Milliseconds undefined (type time.Duration has no field or method Milliseconds)
> The command '/bin/sh -c go get -u -v sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator' returned a non-zero code: 2

The funny thing is that it was working before…on my earlier docker image builds. I rebuilt an image today and it started failing. 
Could you please help me out here? Thanks in advance!

**Comment by walideduc** [comment]
Hello, 
I'm having exactly the same issue, it was working before, and now I have this error too.

**Comment by chuajiesheng** [comment]
Do check you the version of `go` you are using. 
Mine happened on a Ubuntu 18.04.4 LTS and `go version go1.10.4 linux/amd64`.
When I upgrade my `go` to `go version go1.14 linux/amd64` using the [instruction here](https://github.com/golang/go/wiki/Ubuntu) the error went away.

**Comment by absolutarin** [comment]
@walideduc @chuajiesheng Yes, it was working for me back in December or late Nov IIRC. I solved this by updating the alpine docker base image. The current docker image was on go version 1.10.x After carefully reading the error I felt that the method might not have been defined in the old api. Once the latest docker base image was pulled, my go version in the container changed to 1.13.xx. 

`docker build -t <myImageName> . --no-cache` <<--- pulled in the latest docker base image. The `--no-cache` part is important. 

I guess the `sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator` library requires go v1.13 and above. Hope this helps you guys!
