### ISSUE TITLE
Example/docs for using as a library

### ISSUE THREAD

**Issue by mattmoyer** [kubernetes-sigs/aws-iam-authenticator#3]
Add some more docs and a godoc example for https://github.com/heptiolabs/kubernetes-aws-authenticator/blob/master/pkg/token/token.go.

cc @gtaylor

**Comment by StevenACoffman** [comment]
Hello, this would help us as we would like to use a lambda at the end of a codePipeline to deploy applications to an existing EKS cluster, similar to #96

**Comment by StevenACoffman** [comment]
See sample code in issue #133
