### ISSUE TITLE
inconsistent auth behaviour

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes-sigs/aws-iam-authenticator#30]
I'm running the authenticator, and have the role set up correctly. Everything works as expected most of the time, but every X attempt returns:

```
error: You must be logged in to the server (Unauthorized)
```

To test this, I authed with my config like so:

```
export DEFAULT_ROLE="arn:aws:iam::337287630927:role/KubernetesAdmin"
```

Retrieved a token:

```
heptio-authenticator-aws token -i <cluster_name>
```

And then set that token in my `kubeconfig`:

```
kubectl config set-credentials uw2d1-admin --token <my_token>
```

I then ran in a loop, and as you can see, it seems intermittent:

```
while true; do kubectl get nodes; done
error: You must be logged in to the server (Unauthorized)
NAME                                         STATUS     ROLES     AGE       VERSION
ip-10-70-0-106.us-west-2.compute.internal    Ready      master    22d       v1.8.4
NAME                                         STATUS     ROLES     AGE       VERSION
ip-10-70-0-106.us-west-2.compute.internal    Ready      master    22d       v1.8.4
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
NAME                                         STATUS     ROLES     AGE       VERSION
ip-10-70-0-106.us-west-2.compute.internal    Ready      master    22d       v1.8.4
```

How can I go about debugging this?

**Comment by mattmoyer** [comment]
Hi @jaxxstorm, sorry for the delayed response here and sorry to hear you're having issues. The next debugging step I'd do is take a look at the logs from the authenticator daemon. These should be available from `kubectl logs -n kube-system $POD_NAME`.

I'm not sure I have any real ideas about why this is/was happening but I'm interested to find out.

**Comment by baniol** [comment]
The intermittent rejection is due to the fact that the authenticator works only on some of the master nodes. I'd go with inspecting the authenticator pod logs on each master.

**Comment by nakulpathak3** [comment]
I've been running into the same issue. Random `403 Forbidden "could not get token: AccessDenied: Access denied"` errors popping up intermittently.

**Comment by christopherhein** [comment]
@jaxxstorm @nakulpathak3 are you still running into this issue?

**Comment by nakulpathak3** [comment]
I don't have access to the codebase where this occurred anymore. @alexandraj777 might be able to answer that.

**Comment by alexandraj777** [comment]
@christopherhein We have not been using that flow as often for the last few months (we've been focusing on clusters on non-AWS platforms), so I haven't observed this personally over the last few months. I'm keeping an eye out for this when we're back to working with EKS and the AWS authenticators more. 

Thanks @nakulpathak3 for keeping me in the loop 😄
