### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by sujith-siva** [kubernetes-sigs/aws-iam-authenticator#304]
Hi All,

I am trying to connect to the EKS cluster in our dev environment using SAML.
I am having a windows 10 pro laptop.
I have downloaded and installed Docker Desktop(running).
I have installed latest awscli and kubernetes-cli tools
by using choco
 #choco install -y kubernetes-cli
 #choco install -y awscli

I have downloaded the latest aws-iam-authenticator and copied into 
C:\ProgramData\chocolatey\bin

Then run choco install saml2aws --version=2.16.0 to install the SAML version which works for every other users in our environment. Then to connect to the specific cluster I have run the command 
  #saml2aws configure first to configure my saml configuration
  #saml2aws login --force and selected the correct eks cluster where I need to connect.

but somehow after connecting to the specific eks cluster when I try to run kubectl get nodes ,I am getting an error that You must be logged in to the server (Unauthorized).

Also while I am running the kubectl version it is only showing the information regarding the client not for any server version, I have tried re-installing and uninstalling all the components such Docker Desktop and awscli,saml,kubernetes-cli no luck still the error is the same. 

C:\Program Files\Docker\Docker\resources\bin> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)

I don't know how if I try the same AD account from another users laptop working fine.
I don't want to rebuild my laptop just yet assuming it is something to do with the laptop.

so please give me some help.

PS: I am not using the same IAM user who has created the EKS cluster in the aws configure

Thanks
Siv

**Comment by sujith-siva** [comment]
.kube/config

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <..omitted..>
    server: https://CF45THEA48575346D4B024E34FF02F.sk1.eu-west-1.eks.amazonaws.com
  name: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster
- cluster:
    certificate-authority-data: <..omitted...>
    server: https://BV40WAP396A4C595D9508C7644063.yl4.eu-west-1.eks.amazonaws.com
  name: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster2
contexts:
- context:
    cluster: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster
    user: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster
  name: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster
- context:
    cluster: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster2
    user: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster2
  name: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster2
current-context: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster2
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - sivacluster
      command: aws-iam-authenticator.exe
- name: arn:aws:eks:eu-west-1:678923464382:cluster/sivacluster2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - sivacluster2
      command: aws-iam-authenticator.exe

**Comment by gieldb** [comment]
Im not familiar with saml2aws and also did not see you mention aws-auth configmap but [this issue](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/312) might be related/causing this.
