### ISSUE TITLE
API Authorization in javascript from outside a cluster

### ISSUE THREAD

**Issue by stanhordiyenko** [kubernetes-sigs/aws-iam-authenticator#309]
Hi, is there any code in javascript on API Authorization from outside a cluster?

Thank youl

**Comment by micahhausler** [comment]
While this repository only contains the go code, I'm not aware of any Javascript implementations. It should be fairly trivial to reimplement, you can look at the [`pkg/token/token.go`](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/token/token.go#L226-L330) source for how to generate a token. Another example would be the Python implementation in the [AWS CLI](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/eks/get_token.py)
