### ISSUE TITLE
MFA-enforced API keys can still access the cluster without MFA

### ISSUE THREAD

**Issue by sztupy** [kubernetes-sigs/aws-iam-authenticator#322]
I have a user who has everything blocked on his IAM role if they don't use an MFA enabled session token - except obtaining the session token itself for obvious reasons.

        {
            "Sid": "BlockMostAccessUnlessSignedInWithMFA",
            "Effect": "Deny",
            "NotAction": [
                "sts:GetSessionToken"
            ],
            "Resource": "*",
            "Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": "false"
                }
            }
        }

Using this IAM role I can make sure AWS API access is limited as I need to first obtain an MFA enabled temporary credentials before I'm allowed to go further.

However I can still use `kubectl` with this user even with the non-MFA enabled tokens. This constitutes a security risk, as I'd like to make sure I can only access the cluster once I use the MFA-enabled tokens.

**Comment by jacklauritsen** [comment]
see also https://forums.aws.amazon.com/thread.jspa?threadID=294523

**Comment by sztupy** [comment]
Doesn't seem to be any progress on the link as well
