### ISSUE TITLE
github release v0.5.2 does not include executable assets

### ISSUE THREAD

**Issue by dsayling** [kubernetes-sigs/aws-iam-authenticator#344]
v0.5.1 (and previous releases) contained the executables assets in the release for ease of downloading

e.g. in 0.5.1

![image](https://user-images.githubusercontent.com/8107880/95276092-7a06ee80-0807-11eb-9e84-8a152e10b51b.png)

This causes any automation that's depending on the github release to contain the assets to fail.

**Comment by crak-mmarcoux** [comment]
+1 on this!
Urgent matter blocking our production pipelines!

**Comment by allenwei** [comment]
+1

**Comment by dileepfrog** [comment]
+1

**Comment by YukSeungChan** [comment]
+1

**Comment by QUSHLEE** [comment]
+1

**Comment by JaehunYoon** [comment]
+1

**Comment by wiamsuri** [comment]
A quick solution would be to freeze version to `v0.5.1`
For those of you (like me) who came here from CircleCI aws-eks orbs, you can freeze the version by adding.
```
- aws-eks/update-kubeconfig-with-authenticator:
    authenticator-release-tag: v0.5.1
    cluster-name: my-eks-cluster
```

**Comment by jbauerrfid** [comment]
Found the same issue this morning. This causes the CircleCI `aws-eks` orb to fail on command `aws-eks/update-kubeconfig-with-authenticator` unless you specify an older release tag.
-> https://circleci.com/developer/orbs/orb/circleci/aws-eks#commands-install-aws-iam-authenticator
The error output is like:
```
DOWNLOAD_URL="https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/${VERSION}/${FILENAME}_${VERSION_NUMBER}_${PLATFORM}_amd64"

curl -L --fail --retry 3 -o aws-iam-authenticator "$DOWNLOAD_URL"

chmod +x ./aws-iam-authenticator

SUDO=""
if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
  SUDO="sudo"
fi

$SUDO mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

Exited with code exit status 22
CircleCI received exit code 22
```

**Comment by jbauerrfid** [comment]
Hardcoding the version is a valid solution, but I would rather put the version string into the CI environment and reference it in the orb configuration. Otherwise moving to a new versions means to update every repo using it.

**Comment by parkerjm** [comment]
> A quick solution would be to freeze version to `v0.5.1`
> For those of you (like me) who came here from CircleCI aws-eks orbs, you can freeze the version by adding.
> 
> ```
> - aws-eks/update-kubeconfig-with-authenticator:
>     authenticator-release-tag: v0.5.1
>     cluster-name: my-eks-cluster
> ```

unfortunately, if you use `update-container-image`, there appears to be no way to version-lock the aws-iam-authenticator currently: https://circleci.com/developer/orbs/orb/circleci/aws-eks#jobs-update-container-image

**Comment by jbauerrfid** [comment]
with the latest fix from @lokst you can also update the orb:
```
orbs:
  aws-eks: circleci/aws-eks@1.0.1
```
just tested it, this has the same effect

**Comment by owenchak** [comment]
+1

**Comment by nckturner** [comment]
I republished the release with the executables.  

/close
