### ISSUE TITLE
Prebuilt binaries are not included in the latest v0.5.2 release

### ISSUE THREAD

**Issue by sausagee** [kubernetes-sigs/aws-iam-authenticator#345]
In the latest release v0.5.2 that was released yesterday afternoon, it didn't include any prebuilt binaries as previous did. 

Link to latest release
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.2

**Comment by micahhausler** [comment]
Closing as duplicate of #344

/close
