### ISSUE TITLE
Use new AWS public container registry

### ISSUE THREAD

**Issue by Anthonyzou** [kubernetes-sigs/aws-iam-authenticator#356]
It's is kind of annoying to have to install the AWS command line just to pull the image. Would it be possible to switch over to the new public ECR? The flow is more simple.

News here https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/

**Comment by Quarky9** [comment]
FYI I created a public ECR repo at https://gallery.ecr.aws/zero-downtime/aws-iam-authenticator in the meantime.
Alpine based, sources at: https://git.zero-downtime.net/ZeroDownTime/container-park/src/branch/master/aws-iam-authenticator

**Comment by Anthonyzou** [comment]
The public ECR repo seems great!
