### ISSUE TITLE
Require binaries for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [kubernetes-sigs/aws-iam-authenticator#363]
Hi Team,

I am working on building a **cytopia/ansible** image for arm64 but found that it was installing **aws-iam-authenticator** binaries which is not available for ARM64.

I have made some changes in the `.goreleaser.yaml` file in order to build binaries for arm64 platforms.

**commit link:** https://github.com/odidev/aws-iam-authenticator/commit/1868a0d751f5ddd04d0db0c3b81f44b236557f95

I have successfully built the binaries using the command **make build test**.

Do you have any plans to release aws-iam-authenticator for linux-arm64?

It will be very helpful if arm64 binaries are released. If required, I am happy to contribute.

**Comment by morganchristiansson** [comment]
arm64 binaries is available from https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/arm64/aws-iam-authenticator

Use URL from https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html and change amd64 to arm64 in download link.

Why is arm64 binary is not available here also?

**Comment by morganchristiansson** [comment]
Still valid
/remove-lifecycle rotten

**Comment by morganchristiansson** [comment]
Still valid
/remove-lifecycle rotten

**Comment by morganchristiansson** [comment]
Still valid
/remove-lifecycle stale

**Comment by morganchristiansson** [comment]
There are open PRs to add arm64 builds: #391 #417
