### ISSUE TITLE
❓ Interest in controller runtime helpers for TokenReviews?

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/aws-iam-authenticator#364]
👋  long time no chat, would y'all be interested in controller runtime helpers for making `TokenReview` webhook handlers? https://github.com/kubernetes-sigs/controller-runtime/issues/1436 the idea would be you could use controller runtime to maintain your webhooks server and any watchers could be moved away from `client-go` directly to using controller runtime dynamic clients. 

More just asking if this would be useful for the long term on this project, this code base seems pretty stable so I don't know if you'd ever way to replatform to something like CR.

**Comment by nckturner** [comment]
In terms of benefits from migrating, I can see that if you're proposed feature was implemented then we could clean up the server code a little, e.g. the TokenReview stuff [here](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/server/server.go#L342-L352).  Also I'm assuming the main use case for controller runtime in this project would be to reduce the boilerplate in the [CRD controller](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/mapper/crd/controller/controller.go).  Any specific benefits you'd like to call out?  So far I'd say its a nice cleanup but not something we need right away.

**Comment by christopherhein** [comment]
Yeah, the main benefit being able to use Controller Runtimes clients and informers for all the client code within the AWS IAM Authenticator, so where you fetch ConfigMaps, CRs, and any actions that are taken against those would be cleaned up to use a much easier interface as well as a unified cache for them.

An extremely simplified implementation would end up looking something like - https://github.com/kubernetes-sigs/controller-runtime/tree/6ae3ee137e889ca45768139ce7df01ec533c9c55/examples/tokenreview notice that you'd really only need to implement the `Handle` func for doing your verification. So you'd be able to get rid of quite a lot of the boilerplate that is implemented here. EG https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/server/server.go#L252-L286 could be removed and a lot of the server setup code. Along with this, you'd get the benefits of having `cert-watcher` for the server to auto-refresh certs as those change and standardized config management being able to integrate with the componentconfig setup in CR for versioning your configs.

I agree it's a bit of a nice to have since you already have some of these things.

**Comment by nckturner** [comment]
Eh, I wouldn't mind doing it to improve code quality though.  Auto-refreshing certs is also important... good point there.

**Comment by nckturner** [comment]
Not sure what you mean by "unified cache" for the configmaps and custom resources, though.

**Comment by christopherhein** [comment]
> Not sure what you mean by "unified cache" for the configmaps and custom resources, though.

That should just say shared informer cache between both the CRs and the ConfigMaps so you don't have to maintain individual informer caches for those resources. Although I forgot this doesn't use informers for the configmap, it's loaded from disk. so maybe that doesn't matter.
