### ISSUE TITLE
Latest release version "unversioned" probably due to ldflags path

### ISSUE THREAD

**Issue by cho-m** [kubernetes-sigs/aws-iam-authenticator#369]
The latest built binary is currently showing "unversioned" and trying to build in Homebrew using .goreleaser.yaml options is also showing this (https://github.com/Homebrew/homebrew-core/pull/76290):
```console
❯ ./aws-iam-authenticator_0.5.3_darwin_amd64 version
{"Version":"unversioned"}
```

This appears to be due to `ldflags` path:
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/v0.5.3/.goreleaser.yaml#L16
```
-X pkg.Version={{.Version}} -X pkg.CommitID={{.Commit}}
```

Given the import used:
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/v0.5.3/cmd/aws-iam-authenticator/version.go#L8
```
"sigs.k8s.io/aws-iam-authenticator/pkg"
```

The path used in `ldflags -X` will probably require path similar to import like
```
sigs.k8s.io/aws-iam-authenticator/pkg.Version
sigs.k8s.io/aws-iam-authenticator/pkg.CommitID
```

**Comment by calebwoofenden** [comment]
Any update on this?

**Comment by gaffneyd4** [comment]
It looks like this will be fixed moving forward thanks to https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/394

It would still be nice to have the binary rebuilt and re-uploaded so that this issue is fixed though.

@nckturner do you think that would be possible?

**Comment by gaffneyd4** [comment]
When I build locally from the latest commit on master I get the correct version information:
```
➜  aws-iam-authenticator (master) ✔ make bin
...
./_output/bin/aws-iam-authenticator version
{"Version":"v0.5.3","Commit":"4c933f86b1dd7e9b7124542987b4eabb45eaa727","Date":"2021-09-23T15:36:52Z"}
```

**Comment by nckturner** [comment]
This is fixed.
