### ISSUE TITLE
Deb/PPA/Repo/etc - Why not package manager?

### ISSUE THREAD

**Issue by BloodyIron** [kubernetes-sigs/aws-iam-authenticator#370]
Hey so I seem to be the first person on the planet Earth (can't speak for Mars) that wants to see this tool installable from my package manager, _not by downloading an internet binary and copying it into a system-wide binary folder and making it executable_.

Can we please have this tool setup as an installable package in all the major Linux distribution repos? I can already do "sudo apt install awscli", I really want to do the same for aws-iam-authenticator.

Not only for convenience, and security, but also so that my installed version of aws-iam-authenticator gets updates over time too. As it stands right now, the "recommended" methods I see everywhere are download, copy over, forget. And let me tell you, that's a horrible practice for so many reasons. Anyone remember heartbleed? How long do we want to tolerate unpatched versions of aws-iam-authenticator?

Anyways, I really hope this can gain traction, because this really is not the way to do it. Can you please add this to a roadmap in some way?

**Comment by msusta** [comment]
While not really a package manager, there's at least the official container image at https://gallery.ecr.aws/eks-distro/kubernetes-sigs/aws-iam-authenticator
You can set that up as an alias in your shell and through that get an easy way to update it just by pulling a newer tag/latest.

**Comment by rittneje** [comment]
@BloodyIron If you are referring to the command line tool, it hasn't been necessary to install it for some time, as the functionality is built into the standard CLI. https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html
