### ISSUE TITLE
STS calls should be able to be regionalized

### ISSUE THREAD

**Issue by mattlandis** [kubernetes-sigs/aws-iam-authenticator#38]
The default endpoint for STS is hosted in us-east-1 (N. Virginia).  We should allow for the sts request to be generated for the specific region the cluster is in.  This could greatly reduce latency for the call.

[More info on regions](https://docs.aws.amazon.com/general/latest/gr/rande.html#sts_region)

**Comment by mattmoyer** [comment]
Should we allow auto-detection from EC2 metadata, or just hardcoded configuration?

**Comment by mattlandis** [comment]
It depends on if we want to allow requests that we will then make cross-region calls from the authenticator.  We could allow all STS urls.  I don't think it would cause any issues besides latency.

One thing to note is that a user needs to enable region specific sts end points. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

The more I think about it we should make it configurable so that only the regions you have enabled the global endpoint are allowed.

**Comment by nckturner** [comment]
> We should allow for the sts request to be generated for the specific region the cluster is in.

Is this chosen by the client when the token is generated or by the authenticator in server mode deciding where to send the request?

> Should we allow auto-detection from EC2 metadata, or just hardcoded configuration?

If its chosen by the server, then I like the idea of allowing auto-detection from EC2 metadata.  

> One thing to note is that a user needs to enable region specific sts end points. 

Looks like everything is enabled by default, but you have the option to 'disable' specific regional endpoints.

**Comment by mattlandis** [comment]
The URL is part of the signed request so the client needs to determine which URL to use.

**Comment by nckturner** [comment]
I see, so, it would be an argument when generating the token, i.e. `heptio-authenticator-aws token --region us-west-2 ...`, which would get passed to `generator.Get()`?

**Comment by christopherhein** [comment]
This was released in 0.4.0.

**Comment by nckturner** [comment]
The feature in v0.4.0 (https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/173) was actually server-side support for tokens and regional endpoints, so this issue is still relevant.

**Comment by nckturner** [comment]
Implemented in https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/7277af9589e335769272e93d92491f3d0c04be6d
