### ISSUE TITLE
Configuring both OIDC and IAM authentication?

### ISSUE THREAD

**Issue by d-m** [kubernetes-sigs/aws-iam-authenticator#380]
Hello everyone,

We currently use OIDC auth for user-based interactions with Kubernetes (deployed via kops) and IAM auth for automated build deployments. Unfortunately, my team doesn't have any control over this configuration. Is it possible to use this project for IAM auth in conjunction with OIDC auth enabled in the API Server?

Thanks.

**Comment by arruko** [comment]
+1

**Comment by ozbillwang** [comment]
So why not let AWS take the ownership for this OSS?
