### ISSUE TITLE
README.md Slack link broken

### ISSUE THREAD

**Issue by ksquaredkey** [kubernetes-sigs/aws-iam-authenticator#385]
The Slack link at the bottom of README.md  points to "aws-sig", which apparently no longer exists.  When clicked, it just brings up the Kubernetes Slack with whatever the last channel I was on (i.e. external-dns).  Is the correct channel #aws-authenticator?

**Comment by chickenbeef** [comment]
`#aws-sig` was renamed to `#provider-aws`. The README needs to be updated.
