### ISSUE TITLE
[0.5.3] Command "version" does not show version

### ISSUE THREAD

**Issue by Sebor** [kubernetes-sigs/aws-iam-authenticator#389]
Step to reproduce:

- docker run -it alpine sh
- wget https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.3/aws-iam-authenticator_0.5.3_linux_amd64
- chmod +x aws-iam-authenticator_0.5.3_linux_amd64
- ./aws-iam-authenticator_0.5.3_linux_amd64 version

The output is: `{"Version":"unversioned"}`

**Comment by gaffneyd4** [comment]
Duplicate of 369
