### ISSUE TITLE
aws-iam-authenticator token.Expiration is invalid

### ISSUE THREAD

**Issue by surki** [kubernetes-sigs/aws-iam-authenticator#401]
I am using aws-iam-authenticator package (not the CLI) in a client side code
(sample code at the bottom). I was running into an issue periodically where kube
apiserver rejects the calls with 401, then it recovers on its own.

On further analysis, here is what I found:

**tl;dr**: aws-iam-authenticator token becomes invalid as soon as the underlying
assumed role's session expires.

1. *0th minute*: I call `tokenGen.GetWithOptions()` with an existing aws
   session, get the token
    1. As part of this, session's AssumeRole credential provider is called
       and the creds are cached (in AWS SDK) for 15 mins
    2. Set up a token refresher for 12 min from now (well before the expiry
       of 14m)
2. Make Kube api calls ...
3. *12th minute*: I again do `tokenGen.GetWithOptions()`
    1. This leads to `request.Presign()` eventually, which uses the
       credentials cached in step 1.1 (which is valid for another 3 minutes)
    2. Setup a token refresher in 12 min from now again (aka 24th min
       relative to step 1)
4. Make Kube api calls with new token ...
5. *15th minute*: Kube api calls fails with 401
    1. It appears that the token we got fails as soon as the AWS session
       token we got in step 1 expires
6. *24th minute*: call `tokenGen.GetWithOptions()`
    1. Now that the underlying session's cred is expired, AWS SDK
       transparently fetches new credentials and provides it for signing
       (for `request.Presign()`)
7. Kube api calls start working again with the new token
8. If I forcefully expire the AWS session credentials (by calling
   `sess.Config.Credentials.Expire()`) before `tokenGen.GetWithOptions()`,
   everything seems to work as expected

====================

Questions:

1. Is this the expected behavior? Shouldn't the signature be valid for next
   15 mins regardless of the session's cred expiration?
2. What's the correct way to use this package? It appears the expiry value
   mentioned in the aws-iam-authenticator's token.Expiry is sort of not
   telling the "truth": this is going to be invalid as soon underlying AWS
   session creds expire. ?

=========================

<details>
<summary>Example program to reproduce the issue</summary>

How to run:

1. Copy the below main.go into an empty dir
2. Run `go mod init main` and `go mod tidy`
3. Run (replace role arn with a valid one)
   `go run . -assume-role=arn:aws:sts::11111:role/my-role -aws-debug-log`

main.go:

```go
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials/stscreds"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/sts"
	"github.com/go-logr/logr"
	"github.com/go-logr/zapr"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"sigs.k8s.io/aws-iam-authenticator/pkg/token"
)

var (
	assumeRole  string
	region      string
	awsDebugLog bool
)

func init() {
	flag.StringVar(&assumeRole, "assume-role", "", "Role ARN to assume.")
	flag.StringVar(&region, "region", "us-east-1", "AWS region name")
	flag.BoolVar(&awsDebugLog, "aws-debug-log", false, "Enable AWS req/response verbose logging")
}

func main() {
	flag.Parse()

	l := getLogger("development")
	log := zapr.NewLogger(l)
	defer func() { _ = l.Sync() }()

	c, ctx, cancel := setupSignalHandling()
	defer func() {
		signal.Stop(c)
		cancel()
	}()

	sess := getAwsSession(log)

	clusterId := "use1-stage-edge"

	tokenGen, err := token.NewGenerator(true, false)
	if err != nil {
		panic(err)
	}

	verifier := token.NewVerifier(clusterId, "aws")

	var tok token.Token
	fn := func() error {
		log.Info("refreshing token")

		// Uncomment this to force refresh the underlying session
		// credentials.
		//
		// sess.Config.Credentials.Expire()

		var err error
		tok, err = tokenGen.GetWithOptions(&token.GetTokenOptions{
			ClusterID: clusterId,
			Session:   sess,
		})
		if err != nil {
			return err
		}
		log.Info("refreshed token", "expires-in", time.Until(tok.Expiration), "token", tok.Token)
		return nil
	}

	err = fn()
	if err != nil {
		panic(err)
	}

	// Refresh token every 12 mins, verify that token's validity every 30
	// secs
	tokRefresherTicker := time.NewTicker(12 * time.Minute)
	tokVerifyTicker := time.NewTicker(30 * time.Second)

	log.Info("starting")

	for {
		select {
		case <-tokRefresherTicker.C:
			err = fn()
			if err != nil {
				log.Error(err, "error getting token")
			}
		case <-tokVerifyTicker.C:
			log.Info("verifying token", "token", tok.Token)
			id, err := verifier.Verify(tok.Token)
			if err != nil {
				log.Error(err, "token verification failed")
			} else {
				log.Info("token verified", "id", id)
			}
		case <-ctx.Done():
			log.Info("exiting")
			return
		}
	}
}

func getAwsSession(log logr.Logger) *session.Session {
	cfg := aws.NewConfig().
		WithCredentialsChainVerboseErrors(true).
		WithMaxRetries(3).
		WithRegion(region)
	if awsDebugLog {
		cfg = cfg.WithLogLevel(aws.LogDebugWithSigning).
			WithLogger(&logrWrapper{log: log.V(1)})
	}

	sess := session.Must(session.NewSession(cfg))

	if assumeRole != "" {
		log.Info("will assume role", "role", assumeRole)

		sess.Config.WithCredentials(
			stscreds.NewCredentialsWithClient(
				sts.New(sess),
				assumeRole,
				func(p *stscreds.AssumeRoleProvider) {
					p.RoleSessionName = "iam-auth-test"
				},
			))
	}

	return sess
}

func setupSignalHandling() (chan os.Signal, context.Context, context.CancelFunc) {
	var cancel context.CancelFunc
	ctx, cancel := context.WithCancel(context.Background())
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)

	go func() {
		select {
		case <-c:
			cancel()
		case <-ctx.Done():
		}
	}()

	return c, ctx, cancel
}

func getLogger(logfmt string) *zap.Logger {
	var l *zap.Logger
	var err error

	switch logfmt {
	case "production":
		l, err = zap.NewProduction()
	case "development":
		config := zap.NewDevelopmentConfig()
		config.EncoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder
		l, err = config.Build()
	default:
		err = fmt.Errorf("unknown log format: %v", logfmt)
	}
	if err != nil {
		panic(fmt.Sprintf("log initialization failed: %v", err))
	}

	return l
}

type logrWrapper struct {
	log logr.Logger
}

func (l *logrWrapper) Log(msgs ...interface{}) {
	switch len(msgs) {
	case 0:
		return
	case 1:
		l.log.Info(msgs[0].(string))
	default:
		l.log.Info(msgs[0].(string), msgs[:1]...)
	}
}
```
<details>

**Comment by rittneje** [comment]
@surki This is because ultimately it uses presigned URLs to do the authentication, and those will expire in 15 minutes or when the role expires, whichever comes sooner. https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/

The way to handle this is to set `ExpiryWindow` on the `AssumeRoleProvider` to (at least) 15 minutes, so you can know for sure that the presigned URL will always be valid for 15 minutes.

**Comment by surki** [comment]
@rittneje thanks, didn't know about `ExpiryWindow`. Though I am doing something similar to "workaround" this
```
	sess.Config.Credentials.Expire()
	tok, err = tokenGen.GetWithOptions(.&token.GetTokenOptions{ClusterID: "foo", Session: sess})
```

But what I am concerned is the expiry that is mentioned in the returned [token](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/token/token.go#L97) is incorrectly claiming that it will be valid for another 14 minutes, even though it could expire anytime within 15 mins. It seems hard coded [here](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/token/token.go#L85).

Either we should return the expiry `min(15min, sess.Expiry)` or refresh the token internally and then sign the url/return token.

**Comment by rittneje** [comment]
What you really want to know is when the credentials used to generate the presigned URL will expire, but this doesn't get recorded anywhere. (Note that `ExpiresAt` doesn't fit the bill, because it will be tampered with by `ExpiryWindow`.) Consequently, there isn't really a way for this library to set the proper expiration time in all cases.

If you forcibly refresh, then it should work, but only because the minimum role session duration is (coincidentally?) also 15 minutes.

**Comment by surki** [comment]
> What you really want to know is when the credentials used to generate the presigned URL will expire, but this doesn't get recorded anywhere. (Note that ExpiresAt doesn't fit the bill, because it will be tampered with by ExpiryWindow.) Consequently, there isn't really a way for this library to set the proper expiration time in all cases.

Hmm okay. My use case is this is part of a larger operator, doing other things, talking to EKS cluster is just one small part, so the underlying AWS session is being shared/used by multiple packages. The EKS communication is long lived, wanted to keep refreshing the token (which is shared via file system to client-go) before it expires

> If you forcibly refresh, then it should work, but only because the minimum role session duration is (coincidentally?) also 15 minutes.

yes, right, I am setting the session duration to 15 mins manually.
