### ISSUE TITLE
Crash on MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by xubofei1983** [kubernetes-sigs/aws-iam-authenticator#409]
I just upgraded MacOS to Monterey 12.0.1 and failed to run kubectl commands.  Error messages seems related to aws-iam-authenticator

fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x199c671, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff300 sp=0x7ff7bfeff2e0 pc=0x102a535
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff330 sp=0x7ff7bfeff300 pc=0x1027dd3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0xa1 fp=0x7ff7bfeff370 sp=0x7ff7bfeff330 pc=0x102cf11
runtime.rt0_go(0x7ff7bfeff3a0, 0x6, 0x7ff7bfeff3a0, 0x1000000, 0x6, 0x7ff7bfeff5f8, 0x7ff7bfeff60e, 0x7ff7bfeff614, 0x7ff7bfeff617, 0x7ff7bfeff61f, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff378 sp=0x7ff7bfeff370 pc=0x1054a9b
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x199c671, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff300 sp=0x7ff7bfeff2e0 pc=0x102a535
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff330 sp=0x7ff7bfeff300 pc=0x1027dd3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0xa1 fp=0x7ff7bfeff370 sp=0x7ff7bfeff330 pc=0x102cf11
runtime.rt0_go(0x7ff7bfeff3a0, 0x6, 0x7ff7bfeff3a0, 0x1000000, 0x6, 0x7ff7bfeff5f8, 0x7ff7bfeff60e, 0x7ff7bfeff614, 0x7ff7bfeff617, 0x7ff7bfeff61f, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff378 sp=0x7ff7bfeff370 pc=0x1054a9b
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x199c671, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff300 sp=0x7ff7bfeff2e0 pc=0x102a535
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff330 sp=0x7ff7bfeff300 pc=0x1027dd3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0xa1 fp=0x7ff7bfeff370 sp=0x7ff7bfeff330 pc=0x102cf11
runtime.rt0_go(0x7ff7bfeff3a0, 0x6, 0x7ff7bfeff3a0, 0x1000000, 0x6, 0x7ff7bfeff5f8, 0x7ff7bfeff60e, 0x7ff7bfeff614, 0x7ff7bfeff617, 0x7ff7bfeff61f, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff378 sp=0x7ff7bfeff370 pc=0x1054a9b
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x199c671, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff300 sp=0x7ff7bfeff2e0 pc=0x102a535
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff330 sp=0x7ff7bfeff300 pc=0x1027dd3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0xa1 fp=0x7ff7bfeff370 sp=0x7ff7bfeff330 pc=0x102cf11
runtime.rt0_go(0x7ff7bfeff3a0, 0x6, 0x7ff7bfeff3a0, 0x1000000, 0x6, 0x7ff7bfeff5f8, 0x7ff7bfeff60e, 0x7ff7bfeff614, 0x7ff7bfeff617, 0x7ff7bfeff61f, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff378 sp=0x7ff7bfeff370 pc=0x1054a9b
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x199c671, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff300 sp=0x7ff7bfeff2e0 pc=0x102a535
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff330 sp=0x7ff7bfeff300 pc=0x1027dd3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0xa1 fp=0x7ff7bfeff370 sp=0x7ff7bfeff330 pc=0x102cf11
runtime.rt0_go(0x7ff7bfeff3a0, 0x6, 0x7ff7bfeff3a0, 0x1000000, 0x6, 0x7ff7bfeff5f8, 0x7ff7bfeff60e, 0x7ff7bfeff614, 0x7ff7bfeff617, 0x7ff7bfeff61f, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff378 sp=0x7ff7bfeff370 pc=0x1054a9b
Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator failed with exit code 2

**Comment by sarahhodne** [comment]
I'm unable to reproduce this on 12.0.1 using an Intel Mac with the 0.5.3 binaries here: https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.3

Most of the issues raised on [the Go issue tracker](https://github.com/golang/go/issues?q=is%3Aissue+%22fatal+error%3A+runtime%3A+bsdthread_register+error%22) for that error message seems related to anti-virus software, could that be the case for you / does it need an update?

**Comment by chipkillmar** [comment]
We're running an older version, `1.13.7`, which works on macOS Big Sur, but not on Monterey.

```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559

$ curl -o aws-iam-authenticator "https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/darwin/amd64/aws-iam-authenticator"

$ chmod +x aws-iam-authenticator

$ ./aws-iam-authenticator
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x1a923a4, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff348 sp=0x7ff7bfeff328 pc=0x1029781
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff378 sp=0x7ff7bfeff348 pc=0x1027303
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff3e0 sp=0x7ff7bfeff378 pc=0x102c076
runtime.rt0_go(0x7ff7bfeff410, 0x1, 0x7ff7bfeff410, 0x1000000, 0x1, 0x7ff7bfeff640, 0x0, 0x7ff7bfeff658, 0x7ff7bfeff694, 0x7ff7bfeff6d6, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff3e8 sp=0x7ff7bfeff3e0 pc=0x1051c64
```

**Comment by xubofei1983** [comment]
I uninstalled and brew install aws-iam-authenticator with 0.5.3 version.

still same error, exactly as chipkillmar when directly run  aws-iam-authenticator (same os version too).

I do not have additional anti-virus software installed.

**Comment by sarahhodne** [comment]
I can't reproduce it with Homebrew's aws-iam-authenticator either:

```
❯ uname -a
Darwin [redacted] 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

❯ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559

❯ /usr/local/Cellar/aws-iam-authenticator/0.5.3/bin/aws-iam-authenticator version
{"Version":"0.5.3","Commit":"a0516fb9ace571024263424f1770e6d861e65d09"}
```

Maybe it's an ARM vs Intel thing? Though from the stacktrace it looks like @chipkillmar was running Intel (`asm_amd64.s` in the strack trace).

**Comment by xubofei1983** [comment]
Mine is intel too.  exact same message as  @chipkillmar

**Comment by MrLPager** [comment]
I've got the same issue (intel processor) with the same message as @chipkillmar

**Comment by ccannell67** [comment]
From: https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html

I am observing the the brew install method works fine with macOS Monterey.


The AWS-vended version @ `curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/darwin/amd64/aws-iam-authenticator`
does not work on macOS Monterey. 

awsiam % `./aws-iam-authenticator`
```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x2439ce8, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff6f8 sp=0x7ff7bfeff6d8 pc=0x1029781
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff728 sp=0x7ff7bfeff6f8 pc=0x1027303
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff790 sp=0x7ff7bfeff728 pc=0x102c076
runtime.rt0_go(0x7ff7bfeff7c8, 0x1, 0x7ff7bfeff7c8, 0x0, 0x1000000, 0x1, 0x7ff7bfeff980, 0x0, 0x7ff7bfeff998, 0x7ff7bfeff9d4, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff798 sp=0x7ff7bfeff790 pc=0x10527e4
```

Is there an updated AWS vended/distributed version available?
`https://amazon-eks.s3.us-west-2.amazonaws.com/<NEWVERSION?>/bin/darwin/amd64/aws-iam-authenticator`

**Comment by xubofei1983** [comment]
I figured out my issue,  I had another binary of aws-iam-authenticator, which should be old version and failed on MacOS Monterey.   

After I delete old one, and the new aws-iam-authenticator installed with brew works.

So I think @ccannell67  is right, the downloaded binary may broke, but brew install works.

**Comment by Shanmugapriya03** [comment]
I have got the same issue, but i am using `heptio-authenticator-aws`
```
 ~ heptio-authenticator-aws help
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x194b60e, 0x21)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff738 sp=0x7ff7bfeff718 pc=0x1029da1
runtime.goenvs()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff768 sp=0x7ff7bfeff738 pc=0x1027923
runtime.schedinit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff7c0 sp=0x7ff7bfeff768 pc=0x102c664
runtime.rt0_go(0x7ff7bfeff7f8, 0x2, 0x7ff7bfeff7f8, 0x0, 0x1000000, 0x2, 0x7ff7bfeff9a8, 0x7ff7bfeff9c1, 0x0, 0x7ff7bfeff9c6, ...)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff7c8 sp=0x7ff7bfeff7c0 pc=0x1052834
```

**Comment by MrLPager** [comment]
> I figured out my issue, I had another binary of aws-iam-authenticator, which should be old version and failed on MacOS Monterey.
> 
> After I delete old one, and the new aws-iam-authenticator installed with brew works.
> 
> So I think @ccannell67 is right, the downloaded binary may broke, but brew install works.

Thanks! It worked for me.

**Comment by chickenbeef** [comment]
The binary in the EKS docs is still on v0.5.0:

```
./aws-iam-authenticator version
{"Version":"v0.5.0","Commit":"1cfe2a90f68381eacd7b6dcfa2bf689e76eb8b4b"}
```

While the brew package is on 0.5.3: https://formulae.brew.sh/formula/aws-iam-authenticator

I've submitted feedback on the docs to update the link to the latest version.

**Comment by justme-sports** [comment]
Facing this issue still with 12.1 OS
Git version: 2.35.1
Go version: 1.16.13 darwin/amd64 

not able to commit due to the below error: 
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x20594e0, 0x21)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff878 sp=0x7ff7bfeff858 pc=0x1029751
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff8a8 sp=0x7ff7bfeff878 pc=0x10272d3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff900 sp=0x7ff7bfeff8a8 pc=0x102c014
runtime.rt0_go(0x7ff7bfeff930, 0x3, 0x7ff7bfeff930, 0x1000000, 0x3, 0x7ff7bfeffab0, 0x7ff7bfeffabf, 0x7ff7bfeffac3, 0x0, 0x7ff7bfeffacc, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff908 sp=0x7ff7bfeff900 pc=0x1052c64
