### ISSUE TITLE
Build version missing

### ISSUE THREAD

**Issue by rdenchev** [kubernetes-sigs/aws-iam-authenticator#412]
The linux binary is built without version information.

Steps to reproduce:

1. Download the linux cli
`curl -L https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.3/aws-iam-authenticator_0.5.3_linux_amd64`
2. Run
`aws-iam-authenticator version`
3. See output
`{"Version":"unversioned"}`

**Comment by aldredb** [comment]
Same with macOS version
