### ISSUE TITLE
Test flake: TestLoadConfigMap

### ISSUE THREAD

**Issue by sarahhodne** [kubernetes-sigs/aws-iam-authenticator#413]
In https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/410 I hit a flaky test for pkg/mapper/configmap.TestLoadConfigMap: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-iam-authenticator/410/pull-aws-iam-authenticator-unit/1461590927104544768

A rerun seems to have fixed it, and the bot told me to report a flaky test if I found one, so this is that.

I'm not sure what else would be good to report with this, so sorry for this being a bit sparse 😅

**Comment by nckturner** [comment]
Saw another instance of it: 

```
=== RUN   TestLoadConfigMap
time="2022-01-18T17:20:50Z" level=info msg="Received aws-auth watch event"
    configmap_test.go:176: AWS Account '123' not in allowed accounts
    configmap_test.go:180: AWS Account '345' not in allowed accounts
    configmap_test.go:191: Expected to find user 'nic' but got error: User not found in configmap
    configmap_test.go:194: User returned from mapping does not match expected user. (Actual: {UserARN: Username: Groups:[]}, Expected: {UserARN:arn:iam:NIC Username:nic Groups:[system:master]}
time="2022-01-18T17:20:50Z" level=info msg="Received aws-auth watch event"
```
