### ISSUE TITLE
Build aws-iam-authenticator for linux/arm64

### ISSUE THREAD

**Issue by Gearheads** [kubernetes-sigs/aws-iam-authenticator#424]
Helllo:

Would we be able to release this binary for `linux/arm64` architecture?

Currently, I see we only have the following:
-  aws-iam-authenticator_0.5.3_darwin_amd
- aws-iam-authenticator_0.5.3_linux_amd
- aws-iam-authenticator_0.5.3_windows_amd64.exe

My team uses this binary as dependency for another project, and we would like to start supporting ARM64 architecture, such that the following URL resolves:
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${AWS_IAM_AUTH_VERSION}/aws-iam-authenticator_${AWS_IAM_AUTH_VERSION}_linux_arm64

**Comment by Gearheads** [comment]
I think this PR will resolve this issue: https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/425

I am just waiting for it to be merged and released.

**Comment by jyotimahapatra** [comment]
This PR should solve https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/431

**Comment by Gearheads** [comment]
This release helped solved our issue: https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.5

Thank you for the help. Closing this issue.
