### ISSUE TITLE
service account certificate renewal -  token invalid error

### ISSUE THREAD

**Issue by anishpravin** [kubernetes-sigs/aws-iam-authenticator#435]
Hi all
Urgent help:
I am getting invalid token error in the aws-iam-authenticator pods which - increasing the cpu core and restarting/crashing the pods
we started experiencing this issue after renewing the service account cert in the kube-master nodes

**aws-iam-authenticate error**
level=warning msg="access denied" client="127.0.0.1:40222" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate

Any help appreciated
I tried all the steps mentioned below
https://github.com/kubernetes/kubernetes/issues/72026
https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/603

Nothing helped me

**Comment by juris** [comment]
Getting the same issue in API server logs on EKS 1.22. I don't have access to master nodes due to the EKS nature, but it looks like AWS is having the same issues on the masters internally.

CloudWatch EKS API server logs:
```
time="2022-06-10T12:01:49Z" level=warning msg="access denied" client="127.0.0.1:43752" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
time="2022-06-10T12:01:59Z" level=warning msg="access denied" client="127.0.0.1:43752" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
time="2022-06-10T12:02:09Z" level=warning msg="access denied" client="127.0.0.1:43752" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
time="2022-06-10T12:02:19Z" level=warning msg="access denied" client="127.0.0.1:43752" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
time="2022-06-10T12:02:19Z" level=warning msg="access denied" client="127.0.0.1:43752" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
``

**Comment by abhinavttyagi** [comment]
Did anyone solve this issue? I am facing this too.

**Comment by abhinavttyagi** [comment]
@aleksmark I was able to solve this by editing the aws-auth config map. I added ```system:masters``` to role of EKS worker node. After removing ```system:masters``` these errors went away.

**Comment by aleksmark** [comment]
Sorry, @abhinavttyagi  I did not quite get that. The errors started when you added `system:masters` to role of EKS worker node and stopped when you undo that change and removed the `system:masters` group? 

In our case, we don't have `system:masters` group configured for EKS worker node. 

The cluster was running for months without these issues, then we had errors for two days, after that they were just gone and the authenticator started working normally again.

**Comment by abhinavttyagi** [comment]
@aleksmark yes for us issue was that only. 
Did you update some services during that time so that it started to work?

**Comment by aleksmark** [comment]
We haven't done anything to fix it, at least nothing on purpose :)

@nckturner can we reopen this, or I should create a new issue? Or maybe reach out to AWS support? (happened on EKS)

**Comment by aleksmark** [comment]
Our issue was something completely different and non-related to AWS authenticator.

**Comment by optimus-kart** [comment]
@aleksmark facing the same issue, how did you resolve this?

**Comment by Dpkbhatt052** [comment]
what was the issue in your case @aleksmark
