### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by AbimbolaE** [kubernetes-sigs/aws-iam-authenticator#457]
The docker image url listed in the `deploy/example.yml` file points to a private ECR. I recommend pointing this to the official public ECR instead

See original `deploy/example.yml` 
Link: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/2a9ee95fecab59fab41a0b646a63227d66113434/deploy/example.yaml#L231

See suggestion below..
```
image: public.ecr.aws/eks-distro/kubernetes-sigs/aws-iam-authenticator:v0.5.7-eks-1-20-15
```

**Comment by roman-geraskin-m10** [comment]
why is it closed? images from private repo in deploy/example.yml are not available
