### ISSUE TITLE
Role ARNs are normalized on evaluation but not in the config

### ISSUE THREAD

**Issue by mattlandis** [kubernetes-sigs/aws-iam-authenticator#46]
The authenticator normalizes the assumed role that is returned from STS to match the IAM role, but if the RoleARN in the config is defined as a STS assumed role (arn:aws:sts::ACCOUNT:/assumed-role/RoleName/Session) instead of the IAM role (arn:aws:iam::ACCOUNT:/role/RoleName) it will never match.

I am proposing that we normalize the roles defined in the config file when it is loaded to reduce user error.

I am working on a fix if we agree that this is a valid solution.

**Comment by mattmoyer** [comment]
+1, that sounds reasonable.
