### ISSUE TITLE
Root and Federated IAM users may fail to authenticate

### ISSUE THREAD

**Issue by rtripat** [kubernetes-sigs/aws-iam-authenticator#47]
If the token is for a Root or Federated IAM user, then GetCallerIdentity returns ARNs in the following formats respectively
1. arn:aws:iam::123456789012:root
2. arn:aws:sts::123456789012:federated-user/Bob

Canonicalizing these ARNs will fail as they don't match user or assumed-role ARN patterns resulting in a failed authentication. See [here](https://github.com/heptio/authenticator/blob/master/pkg/token/token.go#L309)

Note: I discovered these while reading the code but haven't tested the scenario myself.

Reference
1) Federated IAM user: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html
2) IAM ARN formats: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns

**Comment by mattlandis** [comment]
I am working on PR for this.

**Comment by jonmoter** [comment]
Is this still an issue? We're having trouble authenticating as a federated IAM user (through Okta). It works as long as we create a separate IAM user.

**Comment by nckturner** [comment]
@jonmoter Can you detail your issue a little more?

**Comment by devkid** [comment]
If that helps, we got it to work like this:
```yaml
    - rolearn: arn:aws:iam::1234567890:role/some-role
      username: prefix:{{SessionName}}
      groups:
        - some-group
```

With the `prefix:{{SessionName}}` you can add single users to (cluster) role bindings.
