### ISSUE TITLE
Alternative server log format(s)?

### ISSUE THREAD

**Issue by phillipj** [kubernetes-sigs/aws-iam-authenticator#52]
Have anyone considered supporting other log formats on the server, in addition to the [default logrus.TextFormatter](https://github.com/sirupsen/logrus#formatters)?

As an example, I'm particularly interested in trying the [FluentdFormatter](https://github.com/joonix/log). Although I realise that might be a bigger challenge than simply being able to switch to `logrus.JSONFormatter` as that's built into logrus. I'm a golang rookie, so don't hesitate sharing thoughts around the complexities of both.

If this sounds like a good feature to have, I'd be happy to try and implement it.

**Comment by mumoshu** [comment]
@phillipj Hi! You'll probably want to:

- Move `logrus.SetFormatter` from [here](https://github.com/heptio/authenticator/blob/b53aa08edf33917303e6583f84d6c555739f0bc5/cmd/heptio-authenticator-aws/root.go#L51) to [there](https://github.com/heptio/authenticator/blob/b53aa08edf33917303e6583f84d6c555739f0bc5/cmd/heptio-authenticator-aws/root.go#L66) and
- Add pa global command-line flag to the `heptio-aws-authenticator` command](https://github.com/heptio/authenticator/blob/b53aa08edf33917303e6583f84d6c555739f0bc5/cmd/heptio-authenticator-aws/root.go#L60) to specify the name of logrus log formatter you like

**Comment by phillipj** [comment]
Thanks for your hints, much appreciated!

**Comment by christopherhein** [comment]
Implemented in #73 
/close
