### ISSUE TITLE
[Bug]: aws-iam-authenticator v0.6.2 breaks imports

### ISSUE THREAD

**Issue by notnmeyer** [kubernetes-sigs/aws-iam-authenticator#541]
### What happened?

attempting to upgrade the package to v1.6.2 from v1.6.1 in a go project and i get the following error running `go mod tidy`,

```
➜ go mod tidy
go: downloading sigs.k8s.io/aws-iam-authenticator v0.6.2
go: sigs.k8s.io/aws-iam-authenticator@v0.6.2 requires
	k8s.io/kubernetes@v1.22.0 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

this looks like the same issue that v1.6.0 had, https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/512

### What you expected to happen?

deps install without error

### Anything else we need to know?

v1.6.1 works

### Installation tooling

go install

### AWS IAM Authenticator client version

not relevant

### Client information

```Markdown
- OS/arch: Mac OS 13.1
- kubernetes client & version: v0.25.5
```

### Kubernetes API Version

v1.25.5

### kubeconfig user

```JSON
i don't think this is relevant
```

**Comment by nnmin-aws** [comment]
@notnmeyer Apology for your inconvenience. We are working on the fix. Could you please kindly use v0.5.12 for the moment?

We will let you know when the new release is ready.

**Comment by notnmeyer** [comment]
v0.6.3 seems to work

**Comment by nnmin-aws** [comment]
thank you!
