### ISSUE TITLE
[Feature request]: New release

### ISSUE THREAD

**Issue by zchenyu** [kubernetes-sigs/aws-iam-authenticator#581]
### What would you like to be added?

Many Go packages were updated in https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/547 (merged 2023/01/25) but not yet released in the latest 0.6.2 (released 2022/12/19)

The latest packages should resolve several security vulnerabilities detected by our scanner: 

- https://github.com/advisories/GHSA-69ch-w2m2-3vjp
- https://github.com/advisories/GHSA-69cg-p879-7622
- https://github.com/advisories/GHSA-cg3q-j54f-5p7p

### Why is this needed?

Resolve vulnerabilities from our vulnerability scan

**Comment by dzhulgakov** [comment]
In progress PR: https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/582

**Comment by nnmin-aws** [comment]
apology for your inconvenience, we are working on a new release v0.6.x, will be available soon

**Comment by zchenyu** [comment]
Any update here?

**Comment by zchenyu** [comment]
Bump

**Comment by nnmin-aws** [comment]
apology @zchenyu, we will publish the new release this week hopefully.

**Comment by nnmin-aws** [comment]
@nckturner Could you please kindly help on the release? thank you

**Comment by bryantbiggs** [comment]
this should be resolved now @nnmin-aws / @jyotimahapatra / @dims
