### ISSUE TITLE
Go install fails on v0.6.10

### ISSUE THREAD

**Issue by TJonesy** [kubernetes-sigs/aws-iam-authenticator#600]
[This pr](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/596) caused `go install sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.6.10` to no longer work. It returns the following error:

```
$ go install sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.6.10
go: sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.6.10 (in sigs.k8s.io/aws-iam-authenticator@v0.6.10):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

After some digging I found [this issue](https://github.com/golang/go/issues/44840) which if I understand correctly means that `replace` directives cannot be used in go.mod files that have a main module.

**Comment by kevincantu** [comment]
Hah, reading that Go issue makes me mad!

Anyways for getting my go install of aws-iam-authenticator working, downgrading to `v0.6.9` ([diff](https://github.com/kubernetes-sigs/aws-iam-authenticator/compare/v0.6.9...v0.6.10)) seems to build:
```
go install sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator@v0.6.9
```

**Comment by diist** [comment]
This got broken by this commit: https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/c98f1109162a3c58d9f45bb2ae7994413c8c389f#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Comment by kevincantu** [comment]
Looks as though the go.mod replace directives have been cleaned up and the next release will resolve this, probably.

**Comment by bryantbiggs** [comment]
@nnmin-aws / @jyotimahapatra / @dims we can close this issue now
