### ISSUE TITLE
0.6.11 release was not completed?

### ISSUE THREAD

**Issue by chenrui333** [kubernetes-sigs/aws-iam-authenticator#620]
👋 it looks like 0.6.11 release was not completed (ie the release notes did not get published).  Raise this issue for some awareness. Thanks!

![image](https://github.com/kubernetes-sigs/aws-iam-authenticator/assets/1580956/fc38a7c9-61ba-4004-8534-9acef9a67d76)

relates to https://github.com/Homebrew/homebrew-core/pull/138578

**Comment by dims** [comment]
https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.6.11

thanks @chenrui333

**Comment by chenrui333** [comment]
looks great, thanks!
