### ISSUE TITLE
Make 15-minute token limit configurable

### ISSUE THREAD

**Issue by chrisleck** [kubernetes-sigs/aws-iam-authenticator#63]
15 minutes is annoying short for my dev team's experience.  We use Okta federated AWS authentication, so having to go through the password + 2FA dance every 15 minutes is really asking too much.

**Comment by jsco2t** [comment]
Our team has a similar setup - and have been using the generated `tokens` to perform auth into the `k8s dashboard`. This same 15 minute limitation makes it a serious pain to do any real work with the dashboard.

**Comment by nckturner** [comment]
Increasing the pre-signed URL duration is not something we can do at this point, but let me know if #193 addressed the difficulties around MFA.  It caches the temporary credentials instead of the token.

**Comment by norganna** [comment]
For anyone else affected by this 15 minute limitation that is interested in a sideways hack around this issue, I have created a proxy that performs the regular aws-iam-authentication every 10 minutes for you and injects the tokens into the requests as it forwards them on.

Hopefully one day there will be the ability to authenticate for more than 15 minutes at a time, but for now this solution improves my productivity:

[kdash authenticating dashboard proxy](https://github.com/norganna/kdash)
