### ISSUE TITLE
CVE: PRISMA-2022-0227 in emicklei/go-restful/v3

### ISSUE THREAD

**Issue by sf-nwaller** [kubernetes-sigs/aws-iam-authenticator#635]
Twistlock reports the following vulnerability with aws-iam-authenticator:

**Package:** github.com/emicklei/go-restful/v3
**CVE:** [PRISMA-2022-0227](https://github.com/emicklei/go-restful/issues/497)
**Fix Status:** Fixed in:v3.10.0
**Impacted versions:** <v3.10.0

> github.com/emicklei/go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system.

---

Currently aws-iam-authenticator is bringing in `v3.9.0` as an **indirect** dependency:

https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/4aec898c62bd8277994e224184b21822bb40a70a/go.mod#L31

go-restful v3.10.0 introduced a regression, but v3.11.0 [fixes the vulnerability](https://github.com/emicklei/go-restful/issues/521#issuecomment-1684876345) and also [fixes the regression](https://github.com/emicklei/go-restful/issues/519#issuecomment-1684876181).

Suggestion: `go.mod` should be updated when possible.

**Comment by micahhausler** [comment]
Thanks for the issue. Do you have a real CVE ID to point to? Twistlock/Prisma is a commercial project that the Kubernetes project doesn't have a subscription to, and its not clear that we're actually impacted with the affected symbols as `govulncheck` doesn't identify any issue here.  I'm not opposed to updating dependencies, particularly vulnerable dependencies, but I don't want to quickly make updates just to make an eager scanner happy
