### ISSUE TITLE
Support live reloadable configuration

### ISSUE THREAD

**Issue by mattmoyer** [kubernetes-sigs/aws-iam-authenticator#7]
We should be able to add new role mappings in a ConfigMap and have them reflected without restarting the server.

**Comment by mattmoyer** [comment]
Adding some context here... Whenever a Kubernetes ConfigMap changes, the on-disk representation is automatically updated after a short delay. We just need to write some code to reload the in-memory configuration whenever the config file changes.

The configuration library we're using is spf13/viper which supports dynamic configuration pretty well. Unfortunately the file-watching backend has an issue with how Kubernetes uses symlinks: https://github.com/spf13/viper/issues/284. 

There will also be a little bit of restructuring to make the dynamic changes in Viper reflect into the running configuration. We could have the server internally replace the `http.Handler` with a fresh one every time config changes, or we could wire the Viper object through to the server code.

**Comment by wanghong230** [comment]
+1 For a normal ACL controler, the role and group are keeping changing even though it won't be super frequenctly.

**Comment by christopherhein** [comment]
Is this what we talked about regarding using CRDs rather than the `ConfigMap` on the community call?

**Comment by faheem-cliqz** [comment]
Any updates on this. Will solve the pain of killing pods again and again on configmap updates.

**Comment by christopherhein** [comment]
PR #116 aims to solve this in a different way.

**Comment by argais** [comment]
Big +1 on this one, spent a good couple hours wondering why new mapping weren't working until I went to the logs and saw they weren't reloaded when the cm changes. :/

**Comment by christopherhein** [comment]
@pracucci check out https://github.com/kubernetes-dogs/aws-iam-authenticator/pulls/116 we’re trying to get this to land this week, which will help close this.

**Comment by joekohlsdorf** [comment]
@christopherhein This links to a private repo. Please open the PR against this repo so that we can review it.

**Comment by christopherhein** [comment]
@joekohlsdorf sorry about that it’s already merged into Master and autocorrect rewrote it to “dogs” vs “sigs”
