### ISSUE TITLE
[Feature request]: official helm chart for aws-iam-authenticator

### ISSUE THREAD

**Issue by joaocc** [kubernetes-sigs/aws-iam-authenticator#704]
### What would you like to be added?

* Update aws-iam-authenticator helm chart from the "old" https://github.com/helm/charts/tree/master/stable/aws-iam-authenticator (from https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/198)
* Publish to an official OCI repo (https://gallery.ecr.aws/ for instance)

### Why is this needed?

The old helm chart is not maintained anymore and the repo it is published has long been discontinued

**Comment by omerap12** [comment]
Hey, @joaocc  . I want to publish the chart to Artifact hub under the Kubernetes-sigs publisher. (https://artifacthub.io/packages/search?org=kubernetes-sigs&sort=relevance&page=1)
Can you help with that? or do you want just to have the chart under this repo?

**Comment by joaocc** [comment]
@omerap12 sorry for the delay in answering. Not sure I understand your question, as I don't have any privileges on any of the projects (just a simple potential user of the tech :))

**Comment by jmcgrath207** [comment]
@omerap12 

> (https://artifacthub.io/packages/search?org=kubernetes-sigs&sort=relevance&page=1)
Can you help with that? or do you want just to have the chart under this repo?

Both are great for me. Keep the chart source in the repo for changes and have a helm repo from which to pull. 

FWIW, this helm release action might help.
https://github.com/helm/chart-releaser-action
