### ISSUE TITLE
[Feature request]: v0.5.27 is listed as latest, not v0.6.20

### ISSUE THREAD

**Issue by cpboyd** [kubernetes-sigs/aws-iam-authenticator#720]
### What would you like to be added?

v0.6.20 should be marked as the latest version, and both v0.6.20 and v0.5.27 should have binaries attached (repeat of recurring bug #657)

### Why is this needed?

For anyone that might be programmatically pulling the latest version into Docker images, the build would try to pull v0.5.27 instead of the expected v0.6.20 (granted, both fail currently as there's no binaries)

**Comment by Gearheads** [comment]
Looks like the GitHub Action failed, because of missing credentials?
```
  ⨯ release failed after 5m19s               error=docker images: failed to publish artifacts: failed to push 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.5.27-amd64 after 0 tries: failed to push 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.5.27-amd64: exit status 1: no basic auth credentials
```
https://github.com/kubernetes-sigs/aws-iam-authenticator/actions/runs/8854199394/job/24316751369

**Comment by universam1** [comment]
@bryantbiggs Kind heads up that the release process is broken, thank you
