### ISSUE TITLE
[Assets Availability on Release Tag] Please make downloadable asset for aws-iam-authenticator_TAG_linux_arm64

### ISSUE THREAD

**Issue by anushas-dev** [kubernetes-sigs/aws-iam-authenticator#722]
Hi Team,
Please make downloadable asset for aws-iam-authenticator_TAG_linux_arm64. I am looking for Tag: 0.5.27 
In case it won't be possible, please suggest how to obtain specific binaries? 
It seems like the set of release assets changed after https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.21 (only .zip and .tar.gz are made available)

Thank you

**Comment by svenlange** [comment]
The artefacts für 0.6.20 are also missing.

**Comment by mcramer-billgo** [comment]
+1 on this. Broke our EKS deployment docker files as the compiled binaries are missing from latest .5 and .6 releases.

**Comment by Gearheads** [comment]
Looks like the GitHub Action failed to publish the artifacts for some reason:
```
      • release created/updated
           url=https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.6.20
           published=false
```
https://github.com/kubernetes-sigs/aws-iam-authenticator/actions/runs/8853579891/job/24314748037

**Comment by josh-pius** [comment]
In case it takes a while to fix this, can someone document the steps to build from source in the README.

**Comment by Gearheads** [comment]
> In case it takes a while to fix this, can someone document the steps to build from source in the README.

It looks like we can run the make instruction `build-all-bins` to build from source:
```
make build-all-bins
```
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/Makefile#L90
