### ISSUE TITLE
Create release with 1.10 support

### ISSUE THREAD

**Issue by nckturner** [kubernetes-sigs/aws-iam-authenticator#76]
I propose we create the first release, now that we have a functioning authenticator that supports 1.10 clusters.  

I propose we tag `1.0.0` on the current commit, and create a release with go-releaser.  There has been discussion that folks want support for pre-1.10 clusters without i.e. having to use JQ to remove the JSON.  Ideally I'd like to avoid doing much to support pre-1.10 clusters, perhaps we can tag `0.2.0` on the prior commit, and potentially create a release for it, specifying that this prior release supports pre-1.10 clusters. 

Another tag we can use, in addition or in conjunction, is the format that kubernetes subprojects use, i.e. `kubernetes-1.10.1`, but I doubt it will be necessary to be so explicit about which versions of kubernetes are supported since ideally there are not a lot of releases of the authenticator.  I think kubernetes version compatibility can be addresses in the release notes.

**Comment by mattlandis** [comment]
The one change I would like to see us get in before we cut a 1.0 release is squashing mapUsers/mapRoles into a single map as we discussed during the meeting.  That is the only change I can think of that is in the works which is known to break backwards comparability.

**Comment by nckturner** [comment]
Also, as pointed out by @leosunmo, pre `1.10` users can use `1.10` kubectl with older clusters.

**Comment by leosunmo** [comment]
To add to that, I've been using a Kubectl 1.10 binary as soon as it was released (27th March ish?) against a 1.8.6 cluster. When @christopherhein created his branch with 1.10 external auth I started using that against the same cluster. I have yet to run in to any issues.
