### ISSUE TITLE
Migrate Repository to kubernetes-sigs

### ISSUE THREAD

**Issue by nckturner** [kubernetes-sigs/aws-iam-authenticator#77]
In order to officially become a subproject of SIG-AWS, we need to follow the rules layed out in [kubernetes-repositories](https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md).  

- [x] Migrate into https://github.com/kubernetes-sigs.  
- [x] Must contain the topic for the sponsoring SIG
- [x] Must adopt the Kubernetes Code of Conduct
- [x] All code projects use the Apache License version 2.0
- [x] Must adopt the CNCF CLA bot, merge bot and Kubernetes PR commands/bots
- [x] All OWNERS of the project must also be active SIG members
- [x] SIG membership must vote using lazy consensus to create a new repository
- [ ] SIG must already have identified all of their existing subprojects and code, with valid OWNERS files, in sigs.yaml

Additionally, since its a donated repository: 

- [x] All contributors must have signed the CNCF Individual CLA or CNCF Corporate CLA
- [ ] If (a) contributor(s) have not signed the CLA and could not be reached, a NOTICE file should be added referencing section 7 of the CLA with a list of the developers who could not be reached
- [ ] Licenses of dependencies are acceptable; project owners can ping @caniszczyk for review of third party deps
- [ ] Boilerplate text across all files should attribute copyright as follows: `"Copyright <Project Authors>"` if no CLA was in place prior to donation

**Comment by christopherhein** [comment]
`OWNERS` file closed - https://github.com/heptio/authenticator/pull/78

**Comment by d-nishi** [comment]
#104

**Comment by d-nishi** [comment]
@nckturner please close this issue as this is done. I will update the sigs.yaml next week.

**Comment by nckturner** [comment]
👍
