### ISSUE TITLE
Authenticator CRD & Operator Proposal

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/aws-iam-authenticator#79]
If I'm not wrong this is an alternative to https://github.com/heptio/authenticator/issues/34

### Overview

The current structure of the Heptio Authenticator uses default Kubernetes `ConfigMap` primitives that allow you to add and remove IAM Roles this gives a single point of configuration for the whole lookup table and allows the authenticator to load once and cache the results. The problem is when it comes to updating if you make a change to this file and re-apply it won’t automatically be affected, admins need to reload the `DaemonSet` webhook backend for the new config to load. This proposal came out of the 2018-04-05 community call, The discussion was about the usage of CRDs as a way to make this better. The rest of this document will talk about the specifics of how this could work for the authenticator.

Comments - https://docs.google.com/document/d/1UgSDcMbZdMXLY1SxUtQ7r1puLFdGYF660usGW7AlGwE/edit# 

/cc @nckturner @mattlandis @mattmoyer

**Comment by StevenACoffman** [comment]
The prometheus operator recently made a similar shift, and provided a tool to migrate existing configmaps:
```
go get -u github.com/coreos/prometheus-operator/cmd/po-rule-migration
po-rule-migration \
--rule-config-map=<path-to-config-map> \
--rule-crds-destination=<path-to-rule-crd-destination>
```
0.20 will otherwise automatically convert (upgrade) existing configmaps to crds.

**Comment by christopherhein** [comment]
Awesome @StevenACoffman that feedback is great…

**Comment by christopherhein** [comment]
This could be a nice addition wouldn't be too hard to also have it done in-cluster, so you could pass the name of the `ConfigMap` in most causes `aws-auth` as a flag, and have it pull the list, generate the objects and re-apply them to the cluster.

**Comment by nckturner** [comment]
@christopherhein Let's discuss the feedback on this doc in sig-aws next meeting to move this forward.

**Comment by christopherhein** [comment]
Sounds good!

**Comment by mattlandis** [comment]
@christopherhein I am going to take a stab at the implementation for this feature this week.

**Comment by wanghong230** [comment]
@christopherhein Is the CRD available in EKS cluster?

**Comment by christopherhein** [comment]
> @christopherhein Is the CRD available in EKS cluster?

As far as I know not yet. 

/cc @micahhausler @nckturner

**Comment by galindro** [comment]
@christopherhein is there any plans to make it available on EKS? If yes, is there an ETA?

**Comment by christopherhein** [comment]
> @christopherhein is there any plans to make it available on EKS? If yes, is there an ETA?

/cc @tabern @nckturner @micahhausler

**Comment by dnascimento** [comment]
Any updates on the ETA?
When will be released a new aws-iam-authenticator version with the CRD as well?

**Comment by nckturner** [comment]
We're overdue for an authenticator release so that should come relatively soon, but in terms of bringing this feature to EKS, that is TBD.  If its something you want please add it to https://github.com/aws/containers-roadmap.  I don't think we've had a lot of customers asking for it in EKS so there are currently other higher priorities.

**Comment by galindro** [comment]
Done @nckturner : https://github.com/aws/containers-roadmap/issues/550
