### ISSUE TITLE
error: username or group is not a DNS-1123 hostname

### ISSUE THREAD

**Issue by brosner** [kubernetes-sigs/aws-iam-authenticator#80]
I am seeing this error by largely following the documentation. Groups in example.yaml and from the Kubernetes docs typically have a colon in them. For example `system:masters`. However, this is failing authentication because they don't conform. I am not sure whether I should be changing the group name or if this constraint is either in the wrong place or should be removed altogether?

**Comment by christopherhein** [comment]
@nckturner @mattmoyer I was digging into the username fields in https://github.com/kubernetes/kubernetes and it doesn't look like they have any validation on the field. Do you know of anything different?

**Comment by jutley** [comment]
I just ran into this issue. I do not see anything in Kubernetes that says that usernames have the restrictions that this project imposes. 

The closest thing I could find is the restrictions on [resource names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names), and [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).

Furthermore, our current setup uses users with "Firstname Lastname" as their username, which doesn't match DNS-1123. In the [official documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authentication-strategies), the sample username is an email address (which we would like to move to), which also does not match DNS-1123.

I think this bit of validation needs to be removed. From what I can tell, I think we just need to edit [this code](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/pkg/server/server.go#L340-L346) as follows:
```
template = strings.Replace(template, "{{SessionName}}", identity.SessionName, -1)
```

**Comment by richardmarshall** [comment]
I ran into this as well. Given that k8s doesn't place a dns-1123 restriction on usernames or groups I definitely think this check as well as the replacement of `@`s should be removed.

Additionally the current regex used to check if a user/group name is conforming contains an error. 

```"[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*"```

The expression isn't end/beginning of line anchored so it will match any string that contains a sub-string that is a valid dns-1123 name.

/reopen
/remove-lifecycle rotten
