### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by max-rocket-internet** [kubernetes-sigs/aws-iam-authenticator#97]
Then we could install it just like kops, kubectl etc. Copying a binary from an S3 bucket is not so cool 🙂

**Comment by mattmoyer** [comment]
I think this would be a great idea. The build/release tool we're currently using [supports publishing to a Homebrew tap](https://goreleaser.com/customization/#Homebrew), so this should be pretty easy to stand up.

**Comment by errordeveloper** [comment]
Would be handy for `ekctl` too, although I'm not sure if cross-tap dependencies are supported... Any chance authenticator could be added to Homebrew core?

**Comment by christopherhein** [comment]
Do we have one for `kubernetes-sigs` org? @errordeveloper this project is being moved under there eventually so that would be useful. It doesn't look like it, has that been brought up @spiffxp

We should talk about that being a long-term approach for `eksctl` as well…

**Comment by errordeveloper** [comment]
@christopherhein I have just tried using `goreleaser` to make a homebrew tap for `eksctl`, but had no success due to https://github.com/goreleaser/goreleaser/issues/686.

**Comment by christopherhein** [comment]
So as a method of packaging do you think for sig projects (and incubator separate topic) we could potentially get a repo for a tap? It seems like that would be a useful way for anyone to that makes sig owned projects; would still require a PR but at least we’d be a little more in control of it... might be a much bigger ask then I’m thinking

**Comment by errordeveloper** [comment]
Perhaps we should get back to this topic after the project gets transferred
over.

**Comment by errordeveloper** [comment]
Any updates on this since we've moved to SIG-owned repo?

**Comment by nckturner** [comment]
Not that I know of, @errordeveloper, I wouldn't mind having either a sig-aws specific or kubernetes-sigs tap repository, whatever makes the most sense for the community.  Thoughts?

**Comment by errordeveloper** [comment]
I think tap per Github org would make most sense (i.e.  https://github.com/kubernetes-sigs/homebrew-tap). I cannot think of a good reason of proposing SIG-specific taps, they would be in the same Github org anyway...

**Comment by gabegorelick** [comment]
See https://github.com/Homebrew/homebrew-core/pull/33714

**Comment by max-rocket-internet** [comment]
I think this is done @christopherhein 

```
$ brew install aws-iam-authenticator
==> Downloading https://homebrew.bintray.com/bottles/aws-iam-authenticator-0.4.0.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/7c/7c773fefb0506db8b95ed918ff639ede96b58a4d0d2a51d2faf941f30a61ad84?__gda__=exp=1556526410~hmac=5ee28ee1e8d417d6235dc0f2699e5ce2cb63e4e74adfc007f
######################################################################## 100.0%
==> Pouring aws-iam-authenticator-0.4.0.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/aws-iam-authenticator
Target /usr/local/bin/aws-iam-authenticator
already exists. You may want to remove it:
  rm '/usr/local/bin/aws-iam-authenticator'

To force the link and overwrite all conflicting files:
  brew link --overwrite aws-iam-authenticator

To list all files that would be deleted:
  brew link --overwrite --dry-run aws-iam-authenticator

Possible conflicting files are:
/usr/local/bin/aws-iam-authenticator
==> Summary
🍺  /usr/local/Cellar/aws-iam-authenticator/0.4.0: 5 files, 31.1MB
$
```

Thanks!
